libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SalesforceSDKManagerWithSmartStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/AbstractSmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/EncryptedSmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/PlainSmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartSqlTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreInspectorActivityTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreLoadTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTestCase.java

This ensures every access to the DB goes through ```DBOpenHelper```, which ensures we always access a DB instance that hasn't been closed.

Making SmartStore's backing DB access more stable

---

libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

There doesn't appear to be any good reason to run in the ```:auth``` process. Android doesn't require it either.

Fix for account decryption errors

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

Certificate loading from ```KeyChain``` can not be done from the UI thread. However, the ```WebView``` continues to load the login page in the background, and issues a certificate authentication request callback. But by then, we may not have the alias yet, if the user hasn't made his/her selection yet. This leads to timing issues and failures occasionally. This ensures that the login page is loaded only after the certificate selection has been made, to ensure that we always have the certificate authentication callback covered.

Fix for timing issues with cert based auth

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java

As of 3.0, no scope parameter was put in (even for refresh token) if the scopes array passed in was null or empty
Going back to 3.0 behavior

A couple of tests were broken when getAuthorizationUrl was refactored

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java

SmartStore was crashing if values for integer/floating indexes were null

fix for null "integer" and "floating" SmartStore indexes crash

---

libs/SalesforceSDK/AndroidManifest.xml
libs/SmartStore/AndroidManifest.xml
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SalesforceSDKManagerWithSmartStore.java
libs/SmartSync/AndroidManifest.xml
package.json

The ability to name your own ```SmartStore``` had regressed. This addresses that.

Mobile SDK 3.1.1 Patch Release

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/phonegap/SmartStorePlugin.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java

* Moved ```STORE_CURSORS``` to the ```SmartStore``` class, so that it is per ```SmartStore``` instance.
* Added a ```boolean``` argument that can be passed in for a global database. The default is still the user's database.

Adding support for global SmartStore in hybrid

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/phonegap/SmartStorePlugin.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java

If you call SmartStore's beginTransaction outside a synchronized(store.getDatabase()), you will lock the actual db (because you are in a transaction) without locking the java db object.
Another thread does a smartstore operation at that point, it will lock on the java db object but will be stuck with the db operation because of your transaction. If you attempt to do a smartstore operation then, you will be stuck waiting for that second thread (DEADLOCK!!)
Added a comment to beginTransaction, and added synchronized() {..} in callers of the SDK.
(Maybe this API should go entirely)

SmartStore deadlock fix

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java

If you run a "SELECT * .." smart query and the results include records with non-string fields that have NULL value then the command fails.
```javascript
var smartstore = cordova.require("com.salesforce.plugin.smartstore");
smartstore.registerSoup('testSoup', [{path:"MyString",type:"string"},{path:"MyInt",type:"integer"}], function(res){console.log(res);}, function(err){console.error(err);});
// This works
var upsertArr = [{"MyString" : "1", "MyInt" : 1}];
smartstore.upsertSoupEntries('testSoup', upsertArr, function(res){console.log(res);}, function(err){console.error(err);});
var querySpec = smartstore.buildSmartQuerySpec("select * from {testSoup}");
smartstore.runSmartQuery(querySpec, function(cursor) { console.log(cursor);}, function(err){console.error(err);});
// This fails pre-fix …
```

Bugfix. SmartQuery was failing if an non-string field is NULL

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java

Large POST requests (i.e. file uploads) load all entity content into memory. Android now uses okhttp internally and this is default behaviour. This is a problem if more data is being sent over the network than can fit into an application's heap.
okhttp expects that multipart form uploads give the connection a hint on content length or if content is streaming, set a chunk size. Setting either of these should prevent OOM errors from occurring. This
fix isn't available for SDK users on API levels < 19

Added content length and chunking hints to POST connections

---

.travis.yml
libs/SalesforceReact/build.gradle
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java

I've added the asInputStream() method to RestResponse. In order to keep backwards-compatibility, the `consume()` method should be called in a `finally` block after reading the stream. I've also added `consumeQuietly()` as the IOException in `consume()` will never be thrown with the stream method. 
Here's a Java 6 example:
```java
try {
final InputStream in = restResponse.asInputStream();
// Read the stream (or don't)
} finally {
restResponse.consumeQuietly();
}
```
and a Java 7 example:
```java
try (final InputStream in = restResponse.asInputStream()) {
// Read the stream (or don't)
} finally {
restResponse.consumeQuietly();
}
```
The existing RestResponse methods favor returning null instead of exceptions, so `asInputStream()` will return null if the content has already been streamed …

RestResponses can now be consumed as InputStreams

---

libs/SalesforceHybrid/build.gradle
libs/SalesforceReact/build.gradle
libs/SalesforceSDK/build.gradle
libs/SmartStore/build.gradle
native/NativeSampleApps/RestExplorer/build.gradle
native/NativeSampleApps/SmartSyncExplorer/build.gradle
native/TemplateApp/build.gradle

When the connected Android tests are running, there's no log output and Travis thinks that the build has hung after 10 minutes. This change makes the test task (and only the test task) print out both passed and failed tests. I think that having a 10 minute watchdog is a good idea and it's better to make the  test task more verbose.
Unfortunately due to the way the Android Gradle plugin works, I have to add a snippet of Groovy to each build file instead of being able to add it once in an `allprojects` block.

Switched logging to INFO for connected Android test tasks

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SOQLBuilder.java

Without this fix, the query errors out in languages such as ```Arabic```, since the numerals are localized.

Fixing locale bug with SOQLBuilder

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java

1- Open an Salesforce application (SmartSync explorer example for instance)
2- Let it finish loading and sync down data
3- Turn Airplane mode on
4- Edit a record and click save
5- Turn Airplane mode off
6- Synchronize up records
Result: Synchronization takes a very long time (>20min) or hangs indefinitely 
Expected: Synchronization should happen quickly
PS: Values could be configurable in XML file

Added timeout to fix the following situation (related to issue #1026)

---

libs/SmartStore/build.gradle

The problem with the absolute here (```external...```) is that it doesn't exist in the ```CordovaPlugin```. When ```SmartStore``` is used in the plugin, this is broken. It should be ```libs``` - the binaries in there have symlinks to ```external...``` anyway.

Fixing source directory for SmartStore

---

package.json

While testing with test_force.js I was very puzzled to have all android app generation fail (even though they were working last night). For a while, I thought I had lost something in my recent refactoring.
It turns out that shelljs released v0.6.0 a few hours ago and now forcedroid breaks.
This is a quick fix to make it work again - a better fix would be to revisit our use of shelljs and see how they need to be changed.
People that now install forcedroid and didn't previously have shelljs will run into the issue. So we shouldn't take too long releasing our next release.

Shelljs update is breaking forcedroid

---

libs/SmartStore/libs/armeabi-v7a

We had forgotten to link up ```armeabi-v7a``` (causes issues on ```Samsung Galaxy S6```).

Adding missing architecture for SQLCipher

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java

We were swallowing the response headers, without propagating them upwards.

Adding response headers to Execution

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewEngine.java

The upgrade to MobileSDK 4 has made it impossible to implement `WebView` and `WebViewClient` subclasses for Hybrid apps
I can override `makeWebViewEngine` in my `Activity` ... and implement my own `WebViewEngine` subclass which derives from `SalesforceWebViewEngine`
However, inside my subclass, I'm unable to call the `SystemWebViewEngine` constructors to properly set the appView 
These pass-through constructors are necessary so I can call `super(webView,preferences)` in my subclass the same way `SalesforceWebViewEngine` does

Adds pass-through constructors so Hybrid apps can implement their own WebView and WebViewClient subclasses

---

.gitmodules
hybrid/HybridSampleApps/AccountEditor/src/org/apache/cordova/whitelist/WhitelistPlugin.java
hybrid/HybridSampleApps/NoteSync/src/org/apache/cordova/whitelist/WhitelistPlugin.java
hybrid/HybridSampleApps/SmartSyncExplorerHybrid/src/WhitelistPlugin.java
hybrid/HybridSampleApps/SmartSyncExplorerHybrid/src/org/apache/cordova/whitelist/WhitelistPlugin.java
libs/SalesforceHybrid/res/xml/config.xml
libs/test/SalesforceHybridTest/res/xml/config.xml
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java
libs/test/SalesforceHybridTest/src/org/apache/cordova/whitelist/WhitelistPlugin.java
libs/test/SalesforceSDKTest/res/values/bootconfig.xml
libs/test/SmartStoreTest/res/values/bootconfig.xml
libs/test/SmartSyncTest/res/values/bootconfig.xml
tools/symlink_files.txt

It looks like missing the whitelist plugin and having an invalid refresh token caused the 404.
Adding the whitelist plugin, and still having an invalid refresh token gives a 401 instead.
Removing the whitelist plugin and having a valid refresh token works fine.

Fixing 404 happening in tests

---

.travis.yml

It also fix the build failure that caused by the wrong name for native sample app.

Extend the Travis CI Wait time to make more reliable to completed the test

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java
native/test/TemplateAppTest/src/com/salesforce/samples/templateapp/PasscodeActivityTest.java

Since IME_ACTION_GO action does not trigger a key DOWN and UP key event, so we need to trigger those specific key events by test.

fix fail to submit passcode test issue

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/AlterSoupLongOperation.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartSqlHelper.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartSqlTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreAlterTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreLoadTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTestCase.java

To get them for an existing soup, simply alter the soup passing in the original set of index specs

Soup table will now have db indexes on created and last modified

---

.travis.yml
native/test/TemplateAppTest/src/com/salesforce/samples/templateapp/PasscodeActivityTest.java

And for the smart sync conflict issue for running test for different api versions concurrently, change the PR build on travis ci to one build concurrently for Android. Tried on my fork repo, the total build time will be around 1 and half hour for all supported versions, while the builds are green for all.

Disable the unreliable hybrid test 

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/util/JSONObjectHelper.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/QuerySpec.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/QuerySpecTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFullTextSearchTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTestCase.java

If you specify [path1, path2] you get back [soupElt[path1], soupElt[path2]] for each matching row instead of the soupElt's.

New optional parameter (selectPaths) for query specs

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/AlterSoupLongOperation.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java

Using transactions where we were not (register table, alter soup)

DDL operations are transactional for SQLite

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/AlterSoupLongOperation.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/QuerySpec.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartSqlHelper.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/QuerySpecTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreAlterTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFullTextSearchTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTestCase.java

NB: In the future we should provide a way for developers to use advanced FTS features like selecting the tokenizer (https://www.sqlite.org/fts5.html#section_4_3) or sorting using bm25 (https://www.sqlite.org/fts5.html#section_5_1_1).
Added a way to select FTS4 or FTS5 -- not meant for app but used by tests to make sure no behavior changed.
For a soup created before 4.2, one simply needs to do an alterSoup passing in the original index specs, and the FTS virtual table will be recreated using FTS5 (there is a test for that).

Full-text indexes now using FTS5

---

.travis.yml

I will add hybrid apps later. Right now when the test script creates a hybrid app, it fails on ./install.sh as its trying to do a xcdoebuild. Will have to see how we can build only the android sources and skip the iOS ones.

Add test_force.js to travis file

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncUpTarget.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java

- we shouldn't go to the server for locally created records
- but if the app code unchecks the locally_created flag (e.g. after doing an local update or delete), the smart sync code should not fail the sync up
- added tests

Fix for JSONException at SmartSyncManager:isNewerThanServer

---

.travis.yml
libs/SalesforceSDK/build.gradle
libs/SmartStore/build.gradle
libs/SmartSync/build.gradle
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreJSTest.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartSyncJSTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java

There is a change for create Account name, that we have a generic helper to create record name based on the passed in record type.  While the recent changes checked in not align to that change.
Also enable hybrid tests

Fix a build break

---

gradle.properties
reactnative/ReactNativeTemplateApp/build.gradle

Based on workaround offered here: https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html

Changes to support 64 bits devices with react native

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java

Before 4.2, when we were using Volley, we used to return the Volley Request object which has a method for cancellation.
With OkHttp, cancellation is done through the Call object instead. So it makes sense to return that object instead. Also from the Call object you can get a reference to the Request.
That way, developers don't need to go to the okHttpClient's dispatcher and loop through queuedCalls or runningCalls if they keep a reference to the Call object returned when invoking sendAsync.
However to cancel all requests, it's probably still easier to call cancelAll on the okHttpClient's dispatcher.
@rwhitley

sendAsync returns a OkHttp Call object instead of a Request object.

---

.travis.yml

For android version 22, there are one more "make yourself at home" page shown besides the lock screen after emulator launching, we need to dismissed them before executing ui test.

enable template app ui test

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/DBOpenHelperTest.java

Also added a null check for removeExternalBlobsDirectory if in case it remains null

Populating application's dataDir in constructor of DBOpenHelper

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/Encryptor.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/IndexSpec.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreAlterTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFTSExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFullTextSearchTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTestCase.java

Code to prevent soup from having json1 index and external storage (and new test for it)
1) New tests for externally stored soup with full text
2) New test for delete by query against externally stored soup
3) New tests for alter soup with storage change and column type changes
NB: There doesn't seem to be an API to alter soup with soup spec on Android - so the tests are incomplete (have TODOs) and fail

External storage post merge work (incomplete)

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/AlterSoupLongOperation.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SoupSpec.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreAlterTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreExternalStorageTest.java

Allowed AlterSoupLongOperation to support changing soup spec. This enables a store to be
converted from internal storage to external and vice versa. Storing the new/old soup specs
in the long operations table allows resuming of this kind of operation. If these entries are not found
in the db (in the case of client upgrade), they will be assumed to be internal (see SoupSpec.fromJSON)

Support for changing storage type for alterSoup

---

.travis.yml
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreLoadExternalStorageTest.java

reduce the tested large bytes entry to make it not exceed the maximum external storage supported on emulator

fix the out of memory test failure

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java

Funnily enough, we monitor change in network status, but never propagate those changes anywhere. So, if an app starts offline, we're going to act like network is available.

Fixing network status on Android

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java

NullPointerException: SalesforceAnalyticsManager.getInstance(Account).updateLoggingPrefs() called when not logged in.
- LoginActivity doesn’t always finish with an account. User can back out instead, but SalesforceAnalyticsManager.getInstance() can return null when there isn’t any account.
Steps:
1) Start Login Activity
2) Press back without logging in

NPE: LoginActivity.initAnlayticsManager()

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/Constants.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncOptions.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/ManagerTestCase.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java

Android equivalent of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1887
Added two optional members in SyncOptions: createFieldlist and updateFieldlist.
During sync up:
* created records use createFieldlist if available (and fieldlist otherwise).
* updated records use updateFieldlist if available (and fieldlist otherwise).
Code change very simple.
Tests changes
Tests used to deal with just one field (name) now they deal with multiple fields (name and description).
New tests were added for createUpdatelist and updateFieldlist:
* testSyncUpWithUpdateFieldList
* testSyncUpWithCreateFieldList
* testSyncUpWithCreateAndUpdateFieldList

SyncUp can now have separate fieldlist for create and update

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncDownTarget.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncTarget.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncUpTarget.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/loaders/ContactListLoader.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/objects/ContactObject.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/ui/DetailActivity.java

At the beginning SyncManager dealt with local store and remote server interactions during sync up / down. Then the code was refactored to delegate the remote server interactions to the sync up / down targets (allowing custom targets to read/write from arbitrary end points).
With this PR, the local store interactions are now delegated to the sync targets.
That will allow custom targets to use a different local store and/or flag dirty records differently.
It will also allow supporting syncing sets of related records.

Sync Manager delegates local store interactions to sync targets

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncDownTarget.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncOptions.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncUpTarget.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/TestSyncUpTarget.java

Sync targets are getting "smarter" and SyncManager / SyncOptions are getting simpler - which gives app developers more power (since sync targets can be customized by subclassing) and also will enable us to support sync up / down of related records.
New createOnServer/updateOnServer/deleteOnServer methods expecting record object instead of object type and fields : SyncManager is no longer pulling object type from record or figuring out what fields to save, sync targets handle that.
Kept old createOnServer/updateOnServer/deleteOnServer methods for backwards compatibility (but they are called from the new methods in SyncUpTarget instead of being called from SyncManager).
Moved newly introduced createFieldlist/updateFieldlist from SyncOptions to SyncUpTarget (those fields were introduced in …

SyncManager / sync target / sync options refactor

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

This allows SDK Managers to notify when they are ready.
Also to avoid duplicate notifications.

Moving the Notification out of initInternal 

---

.gitmodules
README.md
external/cordova/cordova.js
hybrid/HybridSampleApps/AccountEditor/assets/www/cordova.js
hybrid/HybridSampleApps/NoteSync/assets/www/cordova.js
hybrid/HybridSampleApps/SmartSyncExplorerHybrid/assets/www/cordova.js
libs/SalesforceHybrid/build.gradle
libs/test/SalesforceHybridTest/assets/www/cordova.js
settings.gradle

This PR:
- switches to using `Cordova 6.1.2` instead of `Cordova 6.1.0`.
- Fetches `Cordova` from `jCenter` instead of consuming it as a submodule.

Switching to Cordova 6.1.2

---

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java

Updated the sendRequest method and associated helper methods to accept objects in bodies instead of simply strings.  Required for posting Feed Elements and to other standard (and custom) endpoints.

Bridge fixed to accepted objects in body

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/EventBuilderHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/config/RuntimeConfig.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java

EventBuilderHelper is doing some not-insignificant work on the same thread it is being called on in many cases from file access to data parsing. This data is not validated to always be compliant, so shouldn't be done in a place that could cause applications to break.
On top of that there are a few methods being called where extra setup work is being done alongside non-eventing code.
RestResponse changes were made because "asString" is not necessarily thread-safe lazy consuming the response body, and in almost all cases if there can be understood that there is data the data would be consumed... so better to have it ready immediately than later.

Moving EventBuilderHelper stuff to run in the background

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

This class shouldn't be using static private properties.  It is crucial that they are instance properties for each Provider created, otherwise if you attempt to have RestClients that are associated with different logged in accounts any but the main account will be completely unable to authenticate.

Fixing an issue with AccMgrAuthTokenProvider

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java

loadSoupBlobAsString creates an incredible amount of temporary objects if used to pick up large json files from the file system.  Immediately after reading the entire file it would then be converted into bytes to be decrypted.
Change skips the initial creation of the string, passing in the bytes directly to decrypt.  On average testing this has flatlined memory use on an app that uses this functionality often.

Fix for memory bloat on temporary objects

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/FileLogger.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/SalesforceLogger.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/logger/FileLoggerTest.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/logger/SalesforceLoggerTest.java

This stores the log levels and file size per component in `SharedPreferences`, so that these preferences are used even if the app is swapped out of memory or the device is restarted.

Adding persistence of logging preferences

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/util/SalesforceHybridLogger.java
libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/util/SalesforceReactLogger.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/util/SmartStoreLogger.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SmartSyncLogger.java

There could be cases where the app extends `SalesforceSDKManager` but uses some hybrid components. If we automatically typecast to `SmartSyncSDKManager`, this would cause a crash. Besides, `appContext` is in the lowest level of the hierarchy anyway.

Logger crash bug fix

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

These APIs do nothing on `API 21` and higher. Since we bumped up our `minVersion` to `API 21`, we don't need them anymore.

Removing deprecated APIs

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java

Also fixing issues with RestClient caches
- no point building a fresh oauth refresh interceptor if a cached ok http client ends up being used
- cleaning cache on logout

Caching auth token right away

---

libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticatorService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

In `Android 8.0 (API 26)`, they have changed the default `AccountManager` permissions accessible to an app. An app must now call `newChooseAccountIntent()`, which will bring up an account picker screen for the user to make a choice, or directly use the custom `Authenticator` for the app's account type. Since we have a custom `Authenticator`, we should use that to access account data instead of calling `accountManager.getAuthToken()`. Directly calling `getAuthToken()` will result in a `SecurityException` being thrown and the app will crash. This PR fixes refactors our access of account data to work on `Android O` in the `Android for Work` environment and some other cleanup. More info here:
- [Android 8.0 Changes](https://developer.android.com/about/versions/oreo/android-8.0-changes.html#aaa …

Fixing auth related crash in Android for Work container on Android O

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java

Once upon a time, we used to pad with the number of pad bytes. https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/d65974a70df81eed6d88109af96f36f937f55fee
Then we stopped doing that. https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/7becd771898d87843dc444dd758d93449199c824
But only the encrypt() method was updated, not the decrypt method.
We were left with that meaningless and actually dangerous code that can throw ArrayIndexOutOfBoundException.
NB: Such exception happened sometimes and a superficial change was made (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/8d9ef6bb45d3129f5a312688bbeee700fef28334).

Removing meaningless code

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticatorService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountManagerTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKManagerTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/HttpAccessTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/ClientManagerTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/ManagerTestCase.java
native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/ExplorerActivityTest.java

Before I send the IDP and SP pull requests out, I wanted to clean up our legacy `OAuth` implementation and start off with a clean base, so I've sent that portion out separately as a pull request.
**Since this PR is large and probably not reviewable, here's a summary of changes I made:**
- Consolidated a bunch of overridden methods that we had accumulated over the years as we added more parameters for features. Most of them were unnecessary and confusing for consumers.
- Removed `client_secret` in any shape, size or form from our codebase, since this is a legacy `OAuth` flow that doesn't apply anymore.
- Removed `clientId` from the `UserAccount` object. This field was never getting populated anyway because we were (incorrectly) assigning the value of `client_secret` to this field.
- All …

Large scale OAuth cleanup

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java

Changes to WebView settings corrects issues with rendering certain 3rd party login screens (e.g., Facebook) See issue #1510.

Fix poor rendering of OAuth login screens

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java

* The syncs soup has a new indexed field (NB: the upgrade scenario is handled by `setupSyncsSoupIfNeeded()` in `SyncState.java`).
* The `createSyncUp(...)` and `createSyncDown(...)` in `SyncState.java` take a new argument `name`. It can be null, but when it is not null, it cannot be the name of an existing sync.
* There is  a new method for getting a sync by name :`byName(...)` in `SyncState.java`
* There are also new methods for deleting a sync by id or name: `deleteById(...)` in `deleteByName(...)` in `SyncState.java`.
* There are tests for the new capabilities in `SyncManagerTest.java`
In the next PR, I will add the ability to get sync by names and also delete syncs from hybrid and react native apps.
In the PR after that, I will add the ability to define syncs from a config file.

Names for syncs 

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/app/SalesforceReactSDKManager.java
libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java
libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/res/layout/sf__dev_info.xml
libs/SalesforceSDK/res/values/sf__strings.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/DevInfoActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityDelegate.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityInterface.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceExpandableListActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceListActivity.java
libs/SmartStore/AndroidManifest.xml
libs/SmartStore/res/layout/sf__inspector.xml
libs/SmartStore/res/values/sf__strings.xml
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/SmartStoreInspectorActivity.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreInspectorActivityTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/ExplorerActivity.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/SmartSyncExplorerApp.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/ui/MainActivity.java

Overview of changes:
* SalesforceSDKManager has a new flag `isDevSupportEnabled`.
It defaults to `BuildConfig.DEBUG`.
When `true`, the menu button keyboard shortcut will bring up a dialog when in a `Salesforce*Activity`.
* The list of actions in the dialog comes  from the method `getDevActions(..)` in `SalesforceSDKManager`. Subclasses of `SalesforceSDKManager` can (and some do) provide more actions.
* Also added a new screen `DevInfoActivity` that shows interesting infos for developers. It can be launched from the new dev support dialog. The data shown comes from the method`getDevSupportInfos()` in `SalesforceSDKManager`. 
Subclasses of `SalesforceSDKManager` can (and some do) provide more data.
Current dev support actions:
* All apps: "Show dev info", "Logout", "Switch User"
* Apps …

Dev support for Mobile SDK

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/SPRequestHandler.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java

This PR closes the loop on the SP side once a `TokenEndpointResponse` is received. It takes this response, hits the identity endpoint, sets PIN policies if they exist, adds the account and switches to it (same as the standard flow). I managed to reuse the existing flow since it was well broken up.

Adding account and completing flow on the SP side

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/config/BootConfig.java
libs/test/SalesforceSDKTest/assets/www/bootconfig_absoluteStartPage.json
libs/test/SalesforceSDKTest/assets/www/bootconfig_relativeUnauthenticatedStartPage.json
libs/test/SalesforceSDKTest/assets/www/bootconfig_remoteDeferredAuthNoUnauthenticatedStartPage.json
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/config/BootConfigTest.java

Per our updated requirements for deferred authentication in hybrid remote apps:
- New property introduced to bootconfig: `unauthenticatedStartPage`.
- Required for deferred authentication in hybrid remote apps.
- Ignored in other configurations (local, remote apps with authentication configured.  Framework will log a warning message in these cases).
- Must be an absolute URL, if present.
- Use of `unauthenticatedStartPage` vs. `startPage` in a remote app with deferred authentication will be based on the internal authentication state of a user.
- If a user has not authenticated, the unauthenticated page will be loaded.
- If the user has authenticated, the original start page will be used.
- Existing `startPage` property represents the "authenticated" path for remote apps, and all paths for …

Adding support for unauthenticatedStartPage hybrid configuration

---

libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPInititatedLoginReceiver.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java

IDP initiated flow works end-to-end now.
Here's the code you need on the IDP side to trigger this flow:
```
final Intent intent = new Intent(IDPInititatedLoginReceiver.IDP_LOGIN_REQUEST_ACTION);
intent.putExtra(IDPInititatedLoginReceiver.USER_HINT_KEY, userHint);
sendBroadcast(intent);
```
This will be in the IDP template app.

Adding helpers for IDP initiated auth flow

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/app/HybridApp.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
native/NativeSampleApps/ConfiguredApp/src/com/salesforce/samples/configuredapp/ConfiguredApp.java
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/RestExplorerApp.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/SmartSyncExplorerApp.java

Use the presence or absence of `idpAppURIScheme` directly to establish if the flow is enabled.

Removing setter for IDP login flow

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPCodeGeneratorActivity.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java

- `ec` may not be the first parameter.
- Removed flapping test due to platform search indexing time.

Fixing a couple of issues

---

hybrid/HybridSampleApps/AccountEditor/AndroidManifest.xml
hybrid/HybridSampleApps/NoteSync/AndroidManifest.xml
hybrid/HybridSampleApps/SmartSyncExplorerHybrid/AndroidManifest.xml
libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
native/NativeSampleApps/ConfiguredApp/AndroidManifest.xml
native/NativeSampleApps/RestExplorer/AndroidManifest.xml
native/NativeSampleApps/SmartSyncExplorer/AndroidManifest.xml

This allows apps that consume through `Maven` to enable browser-based auth as well. Manifest merger will take care of merging this when `Gradle` is used to build.

Moving LoginActivity declarations to app's Manifest

---

libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java

With both "regular" soups and "externally stored" soups.
Test is passing fine so reported [issue](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/338) is not valid.

Adding test to make sure select {soup:_soup} works properly

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceNetworkPlugin.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java

New flag returnBinary (default false) in network plugin sendRequest method.
The native side of the network plugin will send back the base64 encoded body and the content type.

Binary download support

---

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java

New flag returnBinary (default false) in network bridge sendRequest method.
When returnBinary is true the bridge will send back the base64 encoded body and the content type.
Related to: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/52

Binary download support for react native

---

libs/SalesforceAnalytics/build.gradle
libs/SalesforceHybrid/build.gradle
libs/SalesforceReact/build.gradle
libs/SalesforceSDK/build.gradle
libs/SmartStore/build.gradle
libs/SmartSync/build.gradle

I had to update this plugin to solve [this issue](https://github.com/dcendents/android-maven-gradle-plugin/issues/61) with transitive dependencies in libraries with the latest version of `Gradle`.

Updating Maven publish plugin to support Gradle 3.0

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/app/HybridApp.java
libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/app/SalesforceHybridSDKManager.java
libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/app/SalesforceReactSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/app/SmartSyncSDKManager.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/app/SalesforceHybridTestApp.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/TestForceApp.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/TestForceApp.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/TestForceApp.java
native/NativeSampleApps/ConfiguredApp/src/com/salesforce/samples/configuredapp/ConfiguredApp.java
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/RestExplorerApp.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/SmartSyncExplorerApp.java

In `Mobile SDK 6.0` we decoupled encryption from the passcode, thereby making `KeyInterface` unused. It was required in `6.0` for the upgrade. In this PR I'm marking it deprecated, to be removed in `Mobile SDK 7.0`. I have added equivalent `init` methods in the `SDKManager` classes that don't take `KeyInterface` in and marked the existing ones that take `KeyInterface` in deprecated. Also updated the corresponding calls from sample apps and tests. No code changes really.

Marking KeyInterface deprecated for 7.0 and related cleanup

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LoginServerManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/AccountSwitcherActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/FingerprintAuthDialogFragment.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ManageSpaceActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceR.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java

`SalesforceR` is a legacy artifact that we used prior to `Mobile SDK 1.3` (yes, `1.3`) to access resources when we used to ship a `.jar` file. Since then we've switched to shipping as an `Android` library project which includes resources. This PR removes all usage of `SalesforceR` and accesses resources directly instead. It also marks `SalesforceR` deprecated (to be removed in `Mobile SDK 7.0`) -> long overdue.

Deprecating SalesforceR and removing all usage of it

---

libs/SalesforceAnalytics/build.gradle
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/util/test/JUnitReportTestRunner.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/util/test/TimeLimitedTestRunner.java
libs/test/SalesforceAnalyticsTest/AndroidManifest.xml
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/logger/FileLoggerTest.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/logger/SalesforceLoggerTest.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/model/InstrumentationEventBuilderTest.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/security/EncryptorTest.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/store/EventStoreManagerTest.java

`InstrumentationTestCase` has been deprecated. We should be using `InstrumentationRegistry` and the test support library instead - it's faster and more efficient.

First stab at rewriting SalesforceAnalytics tests with new testing framework

---

libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ForceJSTest.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/JSTestCase.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SDKInfoJSTest.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreJSTest.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreLoadJSTest.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartSyncJSTest.java

Hybrid tests run all the javascript tests at once at the beginning saving the results in a static map.
We used to have a method returning the list of of javascript tests to run and a java test method per javascript test. The java test methods were simply getting the saved result.
Now, the running of all the javascript tests happens in the static method annotated with BeforeClass.
The list of tests to run is returned by the data() method and is invoked by the the Parameterized test runner to create an instance of the test class per value. There is only one test method which simply gets the result for the test of this instance.

 Using junit4's parametrized tests in hybrid tests

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceKeyGeneratorTest.java

We are using `Google-java-format` plugin (AOSP style) in Android Studio. That's why there's so many format changes... Any suggestion to improve this?

Added an option to generate an AES-128 key and related unit tests

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java

- put 'consumed = true' into the finally block, so that it will be updated even when there is any exception in the try block. As a result, the same response won't be consumed again when consume() is called later on.
- updated consumeQuietly() to make sure it will swallow any exception.

Fixed the issue that the response can be consumed multiple times.

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncDownTarget.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTargetHelper.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncDownTarget.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncTarget.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTestCase.java
native/NativeSampleApps/SmartSyncExplorer/res/raw/userstore.json

Addressing: https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1339
- During sync down, the sync id is stored in the records.
- During clean ghosts, only records with the given sync id are removed.
- Also updated parent-children clean ghosts.
- Added tests.
NB:
- If you don't have an index on the sync id field, then clean ghosts use the old behavior (delete any records in the soup that would not be returned by a full sync).
- If more than one sync are run into a soup and a record is downloaded by multiple syncs, then the sync id field on that record will have the id of the last sync run. And therefore only running clean ghost for that sync might delete the record.

Clean ghosts should not remove records downloaded by the sync

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

Fixing an issue where this may be null if applicationId or package name is build/flavor dependent.
Original code was in place for issues where release/debug was not consistent in build process for android. Libraries prior to android plugin 3.0 often would be always release.
With android gradle 'implementation' instead of 'compile' library projects would use the same build config as app, so 'BuildConfig.DEBUG' does accurately give back the correct answer in this case.

Fixing a potential NPE when applicationId is configurable in gradle

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/PasscodeManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/FingerprintAuthDialogFragment.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/PasscodeManagerTest.java

**Before:**
- If passcode is enabled, go through `Create` and `Confirm` flows.
- If app is in memory, show fingerprint dialog.
- If app is not in memory, show passcode screen *WITHOUT* fingerprint.
**Now:**
- If passcode is enabled, go through `Create` and `Confirm` flows.
- If app is in memory, show fingerprint dialog.
- If app is not in memory, show fingerprint dialog.
In all cases, fingerprint dialog can fallback on created passcode if the user chooses to.

Remove passcode requirement for app cold start

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java

The encryption padding needs to be set in order for the private key to be used to decrypt data.

Fix issue with decryption using RSA keypair

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

Leaving in the constructor was dangerous because it calls `RuntimeConfig`, which in turn spawns a thread and calls `getInstance()` in `SalesforceSDKManager`. In some cases, that thread could get there before the call from the constructor returns and `INSTANCE` exists. Moving this to the `initInternal()` method guarantees that `INSTANCE` is available when the call to `RuntimeConfig` is made.

Moving IDP runtime config to init call

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/model/InstrumentationEventBuilder.java

This prevents us from sending type as `WiFi;`, since `WiFi` has no sub-type.

Add semi-colon only if sub-type exists

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartSyncPlugin.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTest.java

Before
The smartsync plugin methods for cleanResyncGhosts was returning right away and there was no way to know if/when it completed.
New behavior
cleanResyncGhosts calls its callbacks after finishing (success callback if successful and error callback otherwise).
Done for ios here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2402

cleanResyncGhosts should call its callbacks after finishing

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/PasscodeManager.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/PasscodeManagerTest.java
native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/PasscodeActivityTest.java

Some tests were failing because they were launching `PasscodeActivity` multiple times but we were resetting passcode data in `beforeActivityLaunched()` instead of `setUp()`. I also cleaned up some code in `PasscodeManager`.

Fixing passcode tests and removing unused parameters

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java

I think this doc has always been wrong. `BouncyCastle`, which is the cipher provider we use on `Android` defaults to `128`.

Fixing Javadoc

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java

`EventStoreManager` is lazily instantiated when required, so in some cases, it might be instantiated with `newKey`. This PR explicitly sets it to `oldKey` before the upgrade and `newKey` after the upgrade.

Fixing analytics upgrade step to 6.0

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

`TextUtils.join(".", features)` was throwing `ConcurrentModificationException` in some cases.

Features map should be thread-safe

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java

`communityId` wasn't being used and isn't required in that method.

Removing unused parameter

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/transform/Transform.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AnalyticsPublisher.java

Interface methods don't need an explicit `public` access modifier.

Getting rid of minor warnings

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/config/AbstractPrefsManager.java

The OS caches `SharedPreferences`, so deleting the underlying file without removing the `SharedPreferences` explicitly will result in cached values being written back in.

Removing cached custom attributes upon logout

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java

Allows instantiation of an unauthenticated instance of `SalesforceAnalyticsManager` and storage of global events.

Adding support for storage of unauthenticated analytics

---

.circleci/Dangerfile_PR.rb
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/security/EncryptorTest.java

Some `BouncyCastle` functionality is being removed in `Android P`. Refactored the code to help us pivot from `BouncyCastle` and use `Conscrypt` instead if we want in the future.

Encryption code cleanup to isolate provider

---

hybrid/HybridSampleApps/NoteSync/src/com/salesforce/samples/notesync/ContentSoqlSyncDownTarget.java
libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPRequestHandler.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestRequestTest.java

Analogous to https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2479, changing the "check session" API endpoint to the [user info endpoint](https://help.salesforce.com/articleView?id=remoteaccess_using_userinfo_endpoint.htm), which averts errors due to a user not having API access configured (a common Communities use case).
Android's a little tricker than the iOS work, because `RestRequest` has no context to user-based endpoint configuration.  This approach would add an abstraction to allow the conceptual endpoint to be optionally specified.
**Note:** This is a work in progress.  I didn't want to go any further until the approach was validated.

Adding userinfo endpoint, changing cheap refresh API calls

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/HttpAccessTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/ManagerTestCase.java

Calls to the token endpoint should use `loginUrl`, not `instanceUrl`.

Fixes for tests

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
libs/SalesforceAnalytics/build.gradle
libs/SalesforceHybrid/build.gradle
libs/SalesforceReact/build.gradle
libs/SalesforceSDK/build.gradle
libs/SmartStore/build.gradle
libs/SmartSync/build.gradle
native/NativeSampleApps/RestExplorer/build.gradle

- Upgraded to the latest recommended `Gradle` version.
- Replace `androidTestApi` with `androidTestImplementation`, since `androidTestApi` will be removed by the end of `2018`.

Updating Gradle version and removing deprecated APIs

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java

This PR allows the caller to override the default behavior of attempting to refresh on `HTTP 403` for a given request.

Allow overriding of auto-refresh on HTTP 403

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushNotificationInterface.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCGcmListenerService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCInstanceIDListenerService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCRegistrationIntentService.java

`InstanceID` should be deleted only when the last user account logs out.

Un-registering from GCM push notifications only when the last account logs out

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticatorService.java

`NetworkErrorException` doesn't get thrown anymore, it's a thing of the past.

Fixing some warnings

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java

The `Toast` message wasn't showing because we were attempting to display it from a background thread. We now explicitly call it on the main UI thread.

Fixing Toast not showing for error messages

---

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceOauthReactBridge.java
libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java

The underlying issue is that a flag that indicates logout is in progress is never reset in JS land for deferred authentication. We can't tear down the entire bridge in this use case either. Triggering the callback allows the bridge to reset this flag when logout completes. For more details and discussion, see [this issue](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/72).

Invoking callback for logout

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncUpTarget.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncTarget.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncUpTarget.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTest.java
libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTestCase.java

If a record fails to sync up, the server response is saved in a `__last_error__` field on the record.
NB: That field will be cleared in subsequent successful sync up

Capturing error during sync up on record

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/config/StoreConfig.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/app/SmartSyncSDKManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/config/SyncsConfig.java

setupGlobal/UserStore/SyncsFromConfig no longer calls getSmartStore or getGlobalSmartStore if there is no config (or if it's empty).

setupGlobal/UserStore/SyncsFromConfig no longer calls getSmartStore if no configs

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

There were a number of issues:
* MU feature was never set (on Android) => now it's computed in UserAccountManager.getCurrentAccount()
* addUser event with numUsers attribute was never published (the addUser event with loginServers was however published) => now we published a single addUser event with loginServers and numUsers, I will change the iOS side to also publish a single event 
* user agent attached to out going query was computed when HttpAccess was initialized => now it's computed at request time

Usage tracking fixes

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/app/HybridApp.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
native/NativeSampleApps/ConfiguredApp/src/com/salesforce/samples/configuredapp/ConfiguredApp.java
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/RestExplorerApp.java
native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/SmartSyncExplorerApp.java

This was made available as a filler before the checkbox was available on the connected app endpoint and `.well-known` config.

Remove static method of forcing browser-based auth

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java

This allows for easier subclassing of `PushService` by overriding the methods that create requests for registration and unregistration. In order to specify that the subclass service be used, it has to be specified in the manifest (I've added an example in the Javadoc) and it has to be set with `SalesforceSDKManager.setPushServiceType`. This is because the service is started programmtically in a static method in PushMessaging and we need to know the correct class.
I've also added a callback method for receiving the current registration status. This has been kept protected for subclassing purposes.

PushService is now subclassable

---

build.gradle
libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/build.gradle
libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AnalyticsPublisherService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCInstanceIDListenerService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCRegistrationIntentService.java

Starting with `Android Oreo`, implicit receivers triggering an `IntentService` are no longer allowed in the background. This restriction comes in place only if `targetApiVersion > 26`. Within the SDK there are a few classes that use `IntentService`. However, it is rare that these services are triggered from the background. They are usually deterministically triggered by code when the app is in the foreground.
`Android` has added a new type of service called `JobIntentService` that makes handling any job scheduling requests super easy. This is available in the support library and is backward compatible with old `Android` versions too. Based on the `targetApiVersion` of the app, it automatically determines whether to use `startService()` or `JobScheduler` (introduced in `API 26`) to run the …

Migrating from IntentService to JobIntentService for better job scheduling

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

In some rare cases, it's possible that `peekRestClient()` will throw `AccountInfoNotFoundException`. This could occur if a refresh is kicked off but a logout occurs while that request is in flight from a different thread. The exception thrown by `peekRestClient()` should be handled without the app crashing. This will notify the higher layers that the refresh was unsuccessful (correctly).

Handle exception thrown in some rare cases

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java

We already do this on `iOS` since `APNS` supports it. `GCM` didn't support it, but `FCM` does now.

Adding app's unique application ID for HTTP2 support in FCM

---

libs/SmartStore/res/values/sf__strings.xml
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/SmartStoreInspectorActivity.java

SmartStore inspector was still referring soup_names
It has been renamed to soup_attrs a long time ago
No longer getting query from resource file (bad idea)
Instead building the query using the constants from SmartStore.java
Also showing more rows by default (100 instead of 10)
Showing details soup info if there are 100 soups or less (instead of 10)

Misc fixes for SmartStore inspector

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ManageSpaceActivity.java

Currently user may accidentally touch outside of the dialog, then the dialog is dismissed. This leaves a black screen without any instruction.

Prevent touch outside to dismiss the dialog

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClientHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java

If the org uses a SAML/SSO provider for login, it is possible to customize the SAML/SSO login URL to drop all arguments from the URL. Besides, the login redirect is beyond the control of the Salesforce IDP at this point and hence, the login redirect when a session timeout occurs will not contain `ec=301` or `startURL`. This leaves the user staring at a login page within the hybrid `WebView` that does nothing. Luckily, we can fetch the login URL in this case from `.well-known` and the container needs to do 2 things to solve this problem.
- We need to parse the SSO URLs from `.well-known` (which we already fetch) and check if these URLs are hit as part of the redirects that indicate session timeout.
- If this occurs, load the `startURL`.
This PR addresses these issues.
cc: @khawkins @chrlie …

Fix hybrid remote session refresh case for SAML/SSO login flows

---

.circleci/ci-helper.sh
.circleci/codecov.yml
.circleci/config.yml

Firebase:
- Unit tests run ~3x as fast as CircleCI arm emulators
- Run PRs against Android API 27
- Firebase records the screen and saves logcat during all test runs, you can find that in CircleCI artifacts
- Run nighty tests mon/wed/fri against API 21/23/25
Other improvements:
- Fix tests not running on manual re-run
- Forcefully stop job execution when tests don't need to run (this simplifies later steps)
issues: 
- Code coverage is not being generated

Use Firebase Test Lab 

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java

We had already removed the other legacy upgrade code a while ago. Somehow this was overlooked. A couple of reasons to remove it:
- Without the other code, this is useless anyway.
- In my next PR, I will be switching the hashing from `BouncyCastle` to `Conscrypt` for `Android P`, which means the passcode isn't going to work anyway, so this upgrade step is irrelevant in `Mobile SDK 7.0`.

Removing legacy upgrade code

---

libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java

This fixes 9 test failures in `SmartStore`. There are 2 more failures which will be fixed in my next PR to replace `BouncyCastle` with `Conscrypt` (the failures have nothing to do with `SmartStore` itself).

Replacing deprecated Assert with new signature

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java

Should be `-1` for unspecified `port`.

Fixing bug with KeyChain API call

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCRegistrationIntentService.java

@mdeblase I think this works a little better. This ensures that initialization is performed only once for this app. This covers the case where multiple apps could have registered to `Firebase` on the device.

Tweaking Firebase initialization and adding unique app name identifier

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCRegistrationIntentService.java

FirebaseInstanceId.getInstance() will look for default name, we should now use the scoped appName

Pass Firebase app scoped by appName

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java
libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AnalyticsPublisherService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/EventBuilderHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/SmartStoreInspectorActivity.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/LayoutSyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/MetadataSyncManager.java
libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java

NB: only returning the cached value from a new method (getCachedCurrentUser()). getCachedCurrentUser() should only be used by callers that only care about the user identity (org id, user id) and not the tokens (since they could be outdated).
Locally on simulator, getCurrentUser() runs on average in 34 ms while getCachedCurrent() runs in 0.14 ms.

Caching current user

---

libs/SalesforceReact/build.gradle
libs/SalesforceReact/package.json

Moving to RN 0.56.1, first tried 0.57.1, but ran into an issue (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/commit/1add4778589616feafb9500b91fd5ed005510a0e)
All react tests are passing

Moving to RN 0.56.1

---

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/StoreCursor.java

- smartstore query from hybrid or react native application no longer do any deserialization or serialization in native land / and there is no javascript code change required
- native app only deserialize once the full result is built (*)
(*) probably not faster but that way the code is cleaner (query is calling queryAsString)
now it is very easy to use another JSON library to parse the result set

Avoiding wasteful deserialization/serialization when querying smartstore

---

build.gradle

`Google` moved `Play Services` from `jCenter()` to `google()` (its own internal `Maven` repository). The order matters - `Cordova` made a similar fix earlier this morning.

Fixing compilation error with Play Services

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LoginServerManager.java

Prevents default selected server in shared pref from being incorrect when run config server list is present during first launch initialization.

Check run config servers when initializing

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

Calling `super()` here crashes within `MyCommunities` since most of our use cases are unauthenticated and the list of users would be empty.

Fixing crash in dev dialog for unauthenticated users

---

libs/SalesforceSDK/res/layout/sf__custom_server_url.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java

Reference: https://stackoverflow.com/questions/27447117/indexoutofboundsexception-on-samsung-devices
So far seems to be Samsung only. setText does not work well with OnFocusChangeListener. Needs to delay the UI actions to keep in sync

Replaced setText to android:hint

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

HTTP headers support Latin-1 only. See [this okhttp PR](https://github.com/square/okhttp/issues/891)

Stripped non-printing, non-ASCII chars from user agent 

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

We're using `getCachedCurrentUser()` to get the current user and passing that in via `varargs`. This will be `null` in the unauthenticated use case. We need a `null` check here.

Fix NPE in debug menu

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java

Right now start time is only set on the first run (not during re sync) => our ailtn logs for resyncs have the wrong start time / duration.

Start time should be set when sync goes from not running to running 

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/manager/AnalyticsManager.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java

This is part of the legacy upgrade code that was removed in `7.0`. I seem to have missed these 2 methods somehow.

Removing unused methods

---

libs/SmartStore/build.gradle
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java

Taking the path of least resistance, opening every database with 3.x settings (except of kdf iter, where we are still using 2.x value for performance reason).
We should evaluate if 4.x settings have performance benefits (e.g. the larger page size). 
If they do, we will have to either:
- have code to try 4.x settings first then fall back on 3.x settings if that fails (to open older databases),
- or we should have code (or an API) for migrating older databases to 4.x.

Upgrading to SQLCipher 4.0.1

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/StoreCursor.java

**Problem:**
With the [deserialization optimization](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1798), we routed native smartstore query through queryAsString: we get the full result in a StringBuffer, turn it into a String, then turn that into a JSONArray. So at one point, we have 3 copies on the stack. For large result sets, that cause a out of memory exceptions. 
**To reproduce the OOMs:**
Add the following parameters to SmartStoreLoadTest (and SmartStoreLoadExternalStorageTest)
{"UpsertQuery1StringIndex1000fields1000characters", Type.string, NUMBER_ENTRIES, 1000, 1000, 1}
**Solution:**
Native smartstore query are back to building the result JSONArray incrementally. 
Both query(...) and queryAsString(...) now calls runQuery(...) which expects either a JSONArray or …

Reduced memory usage during smartstore native queries

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClientHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java

In some scenarios such as communities, customers can configure custom login URLs and strip all parameters on the URL without `MyDomain` configured. This would drop `ec=302` in those cases. This PR closes that gap.

Enhancing session timeout rehydration in custom login URL scenarios

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/KeyStoreWrapperTest.java

This PR adds support for generating named `EC` key pairs with key length of `256`. It also adds support for `StrongBox Keymaster` where available (on some devices `API 28` and above).
What's next:
- Encryption and decryption methods that use `EC` keys.
- Encrypting our `AES` encryption key with `EC` keys and storing them in the `KeyStore`.
- Refactoring the code to NOT cache the encryption key in memory and fetch it from the `KeyStore` instead.

Adding elliptical curve (EC) crypto implementation

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java

- Not all users were being logged out after all attempts were used
- Passcode activity was not being dismissed the first time a user tapped forgot passcode

Fix passcode logout issues.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

The `loggedOut` flag was causing issues around some corner cases. We don't need it anymore since there are guardrails around access to that method even if we call `logout` from multiple threads.

Fixing corner case bug around logout of multiple users

---

gradle.properties

This is not supported anymore in the latest version of Gradle.

Removing deprecated NDK usage

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java

Here's the issue:
1. Create an app with `BootConfig.shouldAuthenticate` set to `false` but use a login URL for an org/community that requires authentication.
1. `SalesforceWebViewClientHelper.shouldOverrideUrlLoading` is called, which eventually calls `SalesforceDroidGapActivity.refresh`
1. The REST client has not been initialized yet, leading to a NPE on line 421
To remedy this, the authentication process is manually kicked off if the client is null. Basically, this patch allows an app to recover from a misconfigured org or community that actually requires authentication but whose `BootConfig` says otherwise.
Here's the test matrix I've run this change through:
| shouldAuthenticate | org requires auth | result                         | …

Prevent NPE when refresh is called by shouldOverrideUrlLoading before a REST client has been created

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/files/ConnectUriBuilder.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java

Disabling `StrongBox Keymaster` for now, since it's too slow on `Pixel 3` and `Pixel 3 XL` devices.

Disabling StrongBox Keymaster for now

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java

This should never happen. If the list of files is `null`, most of the SDK wouldn't work anyway.

Adding null check on file list

---

libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/JavaScriptPluginVersionTest.java

Using TextUtils.join instead of String.join
String.join is Java 8 and is not available on older versions of Android

Fixing testJavaScriptPluginVersionsWithNewVersion (only failing on older versions of Android)

---

setversion.sh

brew install gnu-sed --with-default-names is no longer supported so calling gnu-sed by its actual name

Fixing setversion

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java

* added getRuntimeSettings() method
* added test checking runtime settings
* showing runtime settings in dev menu
* fixed test that stopped working (because of larger page size)

Follow up PR for sqlcipher 4 settings

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java

In some rare cases, the generated key can be `null` (if the hardware module, i.e. `Keystore` is unresponsive or unavailable, for instance). It is also device-dependent. If we attempt to insert a `null` value in a `ConcurrentHashMap`, it'll throw an NPE, which is being reported in #1958. This fixes that issue.

Adding checks around generated encryption key

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKManagerTest.java

In some corner cases, an app might want to log out from the background, i.e. with no `Activity` involved. Some examples are:
- from `Settings` screen.
- from a background `Service`.
- from a `Security` screen (where we don't want the screen to be dismissed).
We have always had a flag to support this, but it appears to have regressed at some point, rendering the flag useless. When this flag is set to `false`, we should not dismiss the `Activity` passed in, if any. This PR fixes this issue (and a few warnings).

Fixing a corner case bug/regression with logout from the background

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/test/SalesforceSDKTest/res/values/bootconfig.xml
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java

This PR adds a new API to fetch OpenID token. Using this API requires an OpenID token to be configured on the connected app. It also needs the "openid" scope to be added on the client and the server.

Adding API to fetch OpenID token

---

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/BatchSyncUpTarget.java

That [change](https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/6b34b708b0b4bc8b05ffb5538c9fc32307bd2c9e#diff-2c642ba74807ad55b26b40af627a4d12R120) was not correct because JSONObject throws an exception if the key doesn't exist.

BatchSyncUpTarget was not handling local records without id properly

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java

Fix issue where passcode will not work if bio was enabled for app but later removed from device.
Reported by customer here: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/474

Fix fingerprint deleted bug

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/ClientManagerTest.java

We have a custom `AuthenticatorService` that we use to interact with `AccountManager`. As a result, we use `addAccountExplicitly()` to add accounts to `AccountManager`. However, for removal, we use `removeAccount()`, instead of `removeAccountExplicitly()`. This is because `removeAccountExplicitly()` was introduced in `API 22`, and until this upcoming release, our minimum was `API 21`. Now, our minimum is `API 23`, and we can switch to this new, better-suited API for our account removal. Switching to `removeAccountExplicitly()` is required, because it fixes a bug in our code when `DISALLOW_MODIFY_ACCOUNTS` is set by an MDM provider. Basically, when this flag is set, it allows only programmatic addition and removal of accounts, i.e. through `addAccountExplicitly()` and …

Replacing deprecated removeAccount() calls with removeAccountExplicitly

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

We switched logout from async to sync. As a result, in the multi-user scenario, logging out from an account was causing issues. This is because we attempt to make a `peekRestClient()` call before `isLoggingOut` is reset indicating completion of logout. This fixes the sequence of resetting the flag before sending the intent that logout is complete.

Fixing logout bug with multiple users

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java
native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/ServerPickerActivityTest.java

-  `https://<url>` / `http://<url>` / `<url>` are now all acceptable inputs for custom server url and get added as proper https urls.  
-  Replaced the existing way of verifying label and url (using removed edit server functionality) with a check that the radio button with the proper label and url is displayed in the list.
-  Add tests for no protocol url and rest button.

Make custom server url input more lenient.

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
libs/test/MobileSyncTest/res/raw/usersyncs.json
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/config/SyncsConfigTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTargetTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTargetTest.java

Locally created records providing an external id are upserted during sync up.
* SyncUpTarget and BatchSyncUpTarget both support the new field
* Added test for SyncUpTarget and BatchSyncUpTarget 
* Using the new field in one of the example config and modified config test accordingly
NB:
* ParentChildrenSyncUpTarget does not support it (yet)

Sync up can now provided a external id field name

---

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java

I have playing around with the react-native sdk and just came accross the following.
When uploading a binary file using react native salesforce sdk with the following javascript code
```js
const fileParams = {
VersionData: {
fileMimeType: "image/jpeg",
fileUrl: "file:///storage/emulated/0/DCIM/Camera/IMG_20191010_094041.jpg",
fileName: "IMG_20191010_094041.jpg"
}
};
const payload = {
Title: "Testing file upload title",
Description: "Testing file upload descripton ",
PathOnClient: "IMG_20191010_094041.jpg",
}
const endPoint = "/services/data";
const path = '/v46.0/sobjects/ContentVersion/';
net.sendRequest(endPoint, path, (...args) => {
console.log("Successfully inserted into ContentVersion!!");
console.log(...args);
}, (...args) => {
console.log("Failed to insert into ContentVersion!!"); …
```

Add Content-Type to non-binary parts when building request with fileParams

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java

In some cases, you might need to leave the application and come back to type in a code. For these cases, apps might want to override the default page reload behavior, in addition to overriding back button behavior. This override allows apps to do that.

Added Override for Special Cases of TBID Login Flow

---

libs/SalesforceSDK/build.gradle

Fixes: 
```Static interface methods are only supported starting with Android N (--min-api 24): androidx.browser.trusted.TrustedWebActivityDisplayMode androidx.browser.trusted.TrustedWebActivityDisplayMode.fromBundle(android.os.Bundle)```

Fix project compilation due to androidx browser update.

---

libs/SalesforceAnalytics/build.gradle
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/FileLogger.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/manager/AnalyticsManager.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

- Currently, a single instrumentation event is stored in a single file. As a result, each write creates a new file, and in order to check if max limit of events has been reached, we look up the number of files created.
- As the number of events increases, this approach isn't the best. What we need is a simple key-value store that is fast.
- [Paper](https://github.com/pilgr/Paper) is an open source library that offers this functionality.
- I replaced the existing implementation using `Paper` instead.
- <b>Good news:</b> no public APIs were broken as part of this exercise, so we aren't breaking `semver`.
- Only the internals of reads and writes have been updated.

Replacing Persistence Solution for Instrumentation Events with Paper

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java

Increasing max events to `10000`, now that we have `Paper` to store them instead of individual files.

Increasing max events for AILTN

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

A more comprehensive, better implementation of #2033.
For those special cases like TBID flow, override the following method in `LoginActivity`:
```
protected OAuthWebviewHelper getOAuthWebviewHelper(OAuthWebviewHelperEvents callback,
LoginOptions loginOptions, WebView webView, Bundle savedInstanceState) {
return new OAuthWebviewHelper(this, callback, loginOptions, webView, savedInstanceState);
}
```
Replace the implementation to return the following instead in your subclass of `LoginActivity`:
```
protected OAuthWebviewHelper getOAuthWebviewHelper(OAuthWebviewHelperEvents callback,
LoginOptions loginOptions, WebView webView, Bundle savedInstanceState) {
return new OAuthWebviewHelper(this, callback, loginOptions, webView, savedInstanceState, false);
}
```
This should get the job done.

Fixing advanced auth flow in some cases when you have to leave the app

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/DecrypterInputStream.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/EncrypterOutputStream.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/util/WatchableStream.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/security/EncrypterStreamTest.java

New classes for the `SalesforceAnalytics` library
* `EncrypterOutputStream`: stream to write an encrypted file 
* `DecrypterInputStream`: stream to read an encrypted file 
* `WatchableStream`: interface for streams that can be watched (e.g. when close), useful for instance to time operations when the stream is being read by code outside the sdk
Also added test suite `EncrypterStreamTest`.
NB: Unfortunately encrypted files created the "old" way (using `Encryptor`) cannot be read using a `DecrypterInputStream` because Encryptor base 64 encodes the encrypted bytes. It would be nice to switch to the stream classes for all our encrypted files needs (e.g. external storage for `smartstore`) - for that we need migration code.

Encrypting output stream and decrypting input stream classes

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java

This PR allows subclasses of `SalesforceDroidGapActivity` to override the unauthenticated URL passed to Cordova at runtime. If this method is not overridden, the default value from `BootConfig` is still used for backwards compatibility.
This is the only usage of `unauthenticatedStartPage` in the SDK, so synchronization of the value with `BootConfig` itself shouldn't be needed.

Allowed customization of the unauthenticated start page used by SalesforceDroidGapActivity

---

README.md

Adding a README badge for the Synk vulnerabilities.
Also, moved the badges below the title of the page.
Sample badge:
[![Known Vulnerabilities](https://snyk.io/test/github/forcedotcom/SalesforceMobileSDK-Android/badge.svg)](https://snyk.io/test/github/forcedotcom/SalesforceMobileSDK-Android)

Add a README badge for Snyk

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java

Follow up to [this PR](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2052/). The upgrade steps in that PR would only apply to `SApp` (because of cherry-picking). It would not apply to any other `Mobile SDK` client because I switched the persistent store from single file per event to using `Paper` in the `8.2` timeframe. So, these upgrade steps take events from the old files and move them over to `Paper`, and delete the old files. Tested and verified that it works with our sample apps.

Upgrade Steps for Analytics Data in 8.2

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java

Invert the equality check for process id key to prevent a null pointer exception.

Prevent NPE when comparing process id

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java

This parameter was added to support legacy org migration/split use cases on certain specific APIs. This doesn't apply anymore, and there are more legitimate use cases where this needs to be turned off. The SDK should only refresh on `401` going forward - that's the only legitimate refresh flow now.

Deprecating 'shouldRefreshOn403' for Removal in 9.0

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java

`DownloadManager` can be disabled through `Settings`, and this would prevent a crash within `DownloadManager` if that is the case.

Fixing crash when DownloadManager is disabled

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java

Currently, a `RestRequest` can be built with either `LOGIN` or `INSTANCE` as the base URL. However, it's possible to construct your own `Request` and add `OAuthRefreshInterceptor` while making that request using `OkHttpClient`. Now, in this case, the request could have any base URL, but in the case of instance split, we will automatically change the base URL to the new instance URL, and this will cause the request to fail. `Trailhead GO` was running into this issue with one of their `Heroku` APIs. So, to summarize, we need a check before we swap out the underlying base URL - we should do this only if the existing base URL is `instanceUrl` and if it has changed.
Testing:
- Tested with base URL as `instanceUrl` - `isHostInstanceUrl` was `true` as expected.
- Tested with base URL as a …

Fixing a bug where base URL should not be replaced if it's not instance URL

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

Currently, there's an easy way to refresh tokens from the server, but no single API that does the refresh and handles persisting the new token as well. This adds a convenient way of refreshing and persisting the response. This is useful for apps like `Trailhead GO` that make their own requests using `OkHttpClient`, but need an easy way to refresh tokens in the SDK.

Adding new API for an easy way to refresh and persist auth tokens

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java

For non-API enabled users, it will keep looping every 30 seconds.

Fixing push notification registration retry for external users

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java

Change profile pic path handling to account for the possibility of the external cache dir being null.
https://developer.android.com/reference/android/content/Context#getExternalCacheDir()
> May return null if shared storage is not currently available.
This fix will avoid a `java.lang.SecurityException` with "Unsupported path"

Handle null cacheDir for profile pic

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java

SSO URLs can be configured as SAML providers or auth providers on the Salesforce backend. Currently, we're only fetching the list of SAML providers, but social login is configured through auth providers, such as Facebook, Google, Apple, etc. These should be a part of the SSO URLs list as well to handle all cases.

Adding auth providers in addition to SAML providers to list of SSO domains

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/DecrypterInputStream.java
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/security/EncrypterStreamTest.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/security/EncryptorTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/KeyValueEncryptedFileStoreTest.java

Turns out `CipherInputStream` is a lot slower with `AES-GCM`. While this solution is not particularly good from a memory standpoint, we will need to employ this as a workaround for now, until we figure out how we can achieve acceptable performance with a streaming solution.

Replacing stream encryption/decryption with in-memory solution

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

This PR has 2 enhancements:
- Adds security patch level to the user agent. This allows us to collect data on what patch level our customers are on, which helps us determine what security vulnerabilities they are exposed to.
- Adds the default user agent to the user agent on login webview. I had applied this fix a while ago to our hybrid webview, but hadn't applied it to our login webview. Without this, some SDKs like `Intune` that rely on user agent will not function properly.

User Agent Enhancements

---

gradle.properties
hybrid/HybridSampleApps/AccountEditor/build.gradle
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle
hybrid/HybridSampleApps/NoteSync/build.gradle
libs/MobileSync/build.gradle
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/manager/LayoutSyncManager.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/LayoutSyncDownTarget.java
libs/SalesforceAnalytics/build.gradle
libs/SalesforceHybrid/build.gradle
libs/SalesforceReact/build.gradle
libs/SalesforceSDK/build.gradle
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
libs/SmartStore/build.gradle
native/NativeSampleApps/AppConfigurator/build.gradle
native/NativeSampleApps/ConfiguredApp/build.gradle
native/NativeSampleApps/MobileSyncExplorer/build.gradle
native/NativeSampleApps/RestExplorer/build.gradle

This PR:
- bumps up target API version to `API 30` for all libraries and sample apps.
- bumps up libraries to their latest versions.
- removes methods that were marked deprecated for removal in `9.0`.

Adding Support for Android 11 and Removing Deprecated Methods for 9.0

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncTargetHelper.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/util/ChildrenInfo.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/util/ParentInfo.java
libs/test/MobileSyncTest/res/raw/usersyncs.json
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/config/SyncsConfigTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/SyncManagerTestCase.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncTestCase.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTargetTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/KeyValueEncryptedFileStoreTest.java
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/DetailActivity.java

Locally created parents and/or children providing an external id are upserted during sync up.
* ParentInfo and ChildrenInfo both have the new field,
* Added test for ParentChildrenSyncUpTarget,
* Using the new field in one of the example config and modified config test accordingly,
* Added new methods: SyncTarget.createLocalId() and SyncTarget.isLocalId() - they should be used to get the correct behavior if using id field as the external id field.
The work for other sync up target was done in https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2010.

ParentChildrenSyncUpTarget can now provide an external id field name

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java

Addresses issue outlined in https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008h6aiIAA/view
By insuring the parent onDismiss is called, this ensures the dialog is left in the correct state when dismissed by
the back button or clicking outside the dialog.

@W-8247135 Call parent onDismiss, fixes issue when dismissing dialog

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java

There's a rare situation in `PaperDB` that  causes a crash while attempting to read  a stored event. We have filed an issue with `PaperDB` [here](https://github.com/pilgr/Paper/issues/4). However, in the meanwhile, we need to prevent our applications from crashing in the background while attempting to upload events (there are many crash reports for our internal apps).

Preventing Rare Crash in PaperDB

---

build.gradle
libs/SalesforceSDK/AndroidManifest.xml

According to [Android doc](https://developer.android.com/reference/android/accounts/AccountManager), we don't need this  permission for `API > 22`, and our min API is `23` now. Keeping this permission generates a warning while uploading the app in `Play Store`.

Removing unneeded MANAGE_ACCOUNTS permission

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityDelegate.java

In `SalesforceActivityDelegate`, we replace the usage of Activity Context to build `ClientManager` since it may lead to memory leak when the activity is destroyed. We use Application Context instead.
Using [LeakCanary](https://square.github.io/leakcanary/), we can detect memory leak when the related Activity is destroyed. The reference is kept by the `ClientManager` and its underlaying dependencies.
- Configure [LeakCanary](https://square.github.io/leakcanary/) on your project which imports the Salesforce SDK 
- Start an activity which uses `SalesforceActivityDelegate` such as `SalesforceActivity`
- Quit the activity
- Check the leak does not exist anymore

[BUGFIX] Using app context instead of activity context to avoid memory leak

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/CompositeRequestHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/CompositeResponse.java

SyncUpTarget (single record at a time) was already doing the right thing.
However BatchSyncUpTarget and ParentChildrenSyncUpTarget were not - they were only extracting server id when status code is 201.
Status code will be 201 if record just got created.
However if:
- we are upserting by external id a locally created record
- and the network got disconnected after request was processed by server but before response made it to the client,
- and this is our second attempt to run the sync up
Then the status code will be 200 since the record already exists
See:
- https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3258
- https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm
So the code now checks for success without expecting to find an id in all …

Sync up with external id does not handle locally created records well during replay after network failure

---

libs/SalesforceSDK/res/layout/sf__server_picker.xml
libs/SalesforceSDK/res/values/sf__colors.xml
libs/SalesforceSDK/res/values/sf__strings.xml
libs/SalesforceSDK/res/values/sf__styles.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java

- Add back button to Server Picker action bar to indicate that the user does not need tap a save button.
- Change header text from app name to "Change Server"
- Change add connection button styling from primary to secondary to indicate adding a new connection is not a mandatory action.
- Change url text color to make it more readable.  
This work is pending UX approval.

Update Server Picker UX.

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/app/SalesforceHybridSDKManager.java

Issue was only with hybrid apps (SmartStoreSDKManager, MobileSyncSDKManager and by extension SalesforceReactSDKManager were doing the check already).

Do not instantiate smartstore if there are no syncs or store configs

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java

This fixes an issue where the app will crash if the refresh token was revoked in the background.

Fixing crash when refresh token is revoked from the background

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/MemCachedKeyValueStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/TestForceApp.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManagerTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelperTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/IndexSpecTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/KeyValueStoreInspectorActivityTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/MemCachedKeyValueStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/QuerySpecTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartSqlExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartSqlTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreAlterTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreFTSExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreFullTextSearchSpeedTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreFullTextSearchTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreInspectorActivityTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreLoadExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreLoadTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreLoadTestCase.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreOtherLoadExternalStorageTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreOtherLoadTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTestCase.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SoupSpecTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/StoreConfigTest.java

* Added class MemCacheKeyValueStore (wraps around regular key value store)
* Added interface KeyValueStore (implemented by both KeyValueEncryptedFileStore and MemCacheKeyValueStore)
* Added tests
* Move smartstore tests from package androidsdk.store to androidsdk.smartstore.store to allow access to default members

Key value store that keeps recently accessed values in a in-memory lru cache for faster access

---

libs/SmartStore/res/layout/sf__key_value_inspector.xml
libs/SmartStore/res/values/sf__strings.xml
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/KeyValueStoreInspectorActivity.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/KeyValueStoreInspectorActivityTest.java

Search field can take an exact key or a partial key (using * at the start/end or middle).
When using a partial key, all matching key/value pairs are returned.

Key value inspector now accepts partial key for search

---

.circleci/config.yml

To avoid circular dependencies warning with newer version of node

Upgrading to shelljs 0.8.4

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

This PR fixes a few issues with the hybrid webview.
- We don't need `loadVFPingPage()` anymore. It's inefficient with the hidden webview loading, and doesn't really do anything much anymore, since the `frontdoor` hops we do cover all the scenarios we need. It also slows down load time in hybrid apps.
- I removed `setSidCookies()` as well. It's not required anymore for a few reasons. One reason is because `frontdoor` does its hops and sets the cookies where required. The second reason is because `Google` discourages cookie manipulation by apps in `Chromium` based webviews. The third, and most important reason is that it was actually causing issues with certain community URLs, because when the URL changes the old URL has the old `sid` and the new URL has the new `sid`. This causes an …

Adding Some Enhancements and Fixing Some Issues in Cookie Management

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SoqlSyncDownTarget.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
libs/test/MobileSyncTest/res/raw/usersyncs.json
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/config/SyncsConfigTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/SoqlSyncDownTargetTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestRequestTest.java

There is a way to specify a batch size when doing a SOQL query. See https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_queryoptions.htm
With this PR, we are adding:
- a RestRequest.getRequestForQuery factory method that accepts a batchSize
- an option parameter for SOQLSyncDownTarget to use a different batch size from the default

Adding support for SOQL batch size in RestRequest and in SOQLSyncDownTarget

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClientHelper.java

Sometimes the URL is a `frontdoor` URL, which can contain the `sid`.

Removing potential sensitive URLs from being logged

---

libs/SalesforceAnalytics/build.gradle

They changed the `groupId` of the artifact on `mavenCentral()`. Details [here](https://github.com/pilgr/Paper#migration-to-maven-central).

Fetching PaperDB from mavenCentral() instead of jCenter()

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java

This change allow sequential app-level code to be built around the `FetchAuthConfigTask` (or any other usage of `getMyDomainAuthConfig`)
For instance, one can listen for broadcasts in a subclass of SalesforceDroidGapActivity:
```kotlin
class MainActivity: SalesforceDroidGapActivity {
private val receiver = object : BroadcastReceiver() {
override fun onReceive(context: Context?, intent: Intent?) {
if (intent != null && intent.hasExtra(WAS_REQUEST_SUCCESSFUL_EXTRA)) {
onAuthConfigComplete(intent.getBooleanExtra(WAS_REQUEST_SUCCESSFUL_EXTRA, false))
}
}
}
override fun onStart() {
// Register a receiver before getMyDomainAuthConfig is called in onResume()
registerReceiver(receiver, IntentFilter(AUTH_CONFIG_COMPLETE_INTENT_ACTION))
}
private fun onAuthConfigComplete() { ... }
}
```

Attempts to fetch the auth config will now send a broadcast after they complete.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

`Android for Work` has a relatively new  policy allowing admins to disable users from adding accounts. However, apps should still be allowed to add user accounts, even if this policy is disabled. The correct way to handle this is by ensuring that apps don't call `addAccount` directly, and only call `addAccountExplicitly`. This PR ensures that `Mobile SDK` is compliant with this policy, by only using `addAccountExplicitly` as the API is designed to be used.

Fixing bug with Android for Work where addition of accounts is disabled by the admin

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartSqlHelper.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartSqlTest.java

Before json1, smartstore indexing / querying worked by having dedicated columns for all indexed fields.
So given a query like select {soup:field} from {soup} would turn into select TABLE_0_1 from TABLE_0.
For json1, indexed fields are functional indexes on the json soup field itself e.g. json_extract(soup, $.field).
We have a table to keep track of indexed fields, it contains the column name where the indexed data is extracted. But for json1, it simply contains that expression.
A problem arises for queries with a table specifier e.g, if you do a join: select soupL.{soup:field}, soupR.{soup:field} from {soup} as soupL, {soup} as soupR
If field does not use json1, the generated SQL is select soupL.TABLE_0.TABLE_0_1, soupR.TABLE_0.TABLE_0_1 from TABLE_0 as soupL, TABLE_0 as soupR which is …

Faster regexp for smartsql to sql conversion

---

hybrid/HybridSampleApps/AccountEditor/AndroidManifest.xml
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/AndroidManifest.xml
hybrid/HybridSampleApps/NoteSync/AndroidManifest.xml
libs/SalesforceHybrid/res/xml/config.xml

- main activity cannot be exported false
- config.xml needs (dummy) content property otherwise one gets a NPE at runtime (because of change introduced by https://github.com/apache/cordova-android/pull/1298)
- CordovaActivity extends AppCompatActivity so must use AppCompat theme (see https://github.com/apache/cordova-android/pull/1052)

Fixing sample hybrid apps with new cordova

---

libs/SalesforceSDK/build.gradle
libs/test/SalesforceHybridTest/AndroidManifest.xml
libs/test/SalesforceHybridTest/res/xml/config.xml
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java

- Fixing hybrid tests - see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2237/commits/790f9d24ac0df2cf1381b5ea1b019b257327588f)
- Fixing test failures in AuthConfigUtilTest that happens on API 23 - see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2237/commits/2b94285edf19540b01953723433b5acc4de31e55)

Fixing tests

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java

Exception was thrown by `Encryptor.getStringFromStream()` when doing
```java
return output.toString(String.valueOf(StandardCharsets.UTF_8));
```
- It turns out the implementation of Charset.toString() on [23](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-23/blob/master/java/nio/charset/Charset.java#L546) is:
```java
return getClass().getName() + "[" + this.canonicalName + "]";
```
- And on [24](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-24/blob/master/java/nio/charset/Charset.java#L966)+ it is:
```java
return name()
```
Call `name()` instead of `toString()` (or `String.valueOf()` which itself calls `toString()`).

Fixing IOException in RestClientTest happening on API 23 only

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/KeyValueStoreInspectorActivity.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTest.java

The issue was reported here: https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2167
If no value is found, no field is sent to the server.
If the node is found but has no value, the field is sent to the server with null as value.
The SyncUpTarget on iOS was already behaving that way, see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/MobileSync/MobileSync/Classes/Target/SFSyncUpTarget.m#L233
Instead of changing SmartStore.project to start returning JSONObject.NULL, we introduced a new project method projectReturningNULLObject that has the new behavior. That method is called from SyncUpTarget's buildFieldsMap.

Making null handling consistent with iOS during sync up

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

With `targetApi = 31`, we now need to explicitly specify if a `PendingIntent` is  mutable or immutable, otherwise it will cause a runtime crash. We would use `FLAG_IMMUTABLE` in most cases, except for use cases like message bubbles where the contents need to be frequently updated.
The crash would look like this:
```
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

Adding required flags by API 31 for PendingIntent

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/ScreenLockManager.java

There are code paths that may call `logout()` in `SalesforceSDKManager` with a `null` user account. Since `cleanUp()` is always called from there, we need to check if the user account instance is `null` before calling `getUserLevelFilenameSuffix()` to prevent an NPE from happening (happens in `Communities` due to guest user experience scenarios).

Fixing crash in ScreenLockManager

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTest.java

The SQLite Write Ahead Logging is enabled for all SmartStore DB objects.
This is a small but impactful change to how the underlying SQLite DB objects function.  The benefits seem to be measurable, repeatable, and significant.  The head of my [sandbox/perf-testing](https://github.com/gkotula/SalesforceMobileSDK-Android/tree/sandbox/perf-testing) has a [simple upsert test](https://github.com/gkotula/SalesforceMobileSDK-Android/blob/f8b6740afc5a407f77fead8e02306d266804f3be/benchmarking/src/androidTest/java/com/salesforce/androidsdk/benchmarking/SmartStoreBenchmark.kt#L63) in a tight loop which sees a ~5x average speed increase with WAL enabled compared to without.
Further investigation for the performance impacts could be done, but between these results and the work that others have done, it …

Enables WAL in SmartStore

---

libs/SalesforceAnalytics/build.gradle

Upgrade of paperdb dependency to version 2.7.2.
When R8 is enabled, starting from Android Gradle Plugin 7.0.2, there is a crash when using paperdb. It prevents us from upgrading Android Gradle Plugin to a more recent version. For the full context, see https://github.com/pilgr/Paper/issues/196.
- Generate new archives for the SDK modules
- Use these archives as dependencies
- Update the app to Android Gradle Plugin 7.0.4 
- Generate a new app version in release mode with R8 enabled
- Update existing version of the app using this new version
I have not seen any regressions and this new version of the lib seems to fix the problem. 
I have seen that paperdb is used for Analytics events in the SDK but I may have missed some impacts due to this change. Is it possible that you check everything …

Upgrading paperdb lib to 2.7.2

---

libs/SmartStore/build.gradle
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTestCase.java

Only issues encountered in tests, the explain query plan is a bit different e.g. saying "SCAN tableName ..." instead of "SCAN table tableName etc".

Moving to SQLCipher 4.5.0

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java

Old implementation was calling encryptStreamToFile so saving a few lines but that meant that the string was fed into a byte array input stream and then read from that stream a byte at a time only to be reconstituted to a byte array.

More efficient kv write method

---

libs/SalesforceReact/build.gradle
libs/SalesforceReact/package.json

This is fixes a crash for Android release builds.

Bump React Native to 0.67.1.

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/store/EventStoreManagerTest.java

storeEvent() calls shouldStoreEvent() which calls getNumStoreEvents() which calls book.getAllKeys().size() which gets slower the more events are stored
Fix: keep a count in memory and only go to disk the first time around
Also added asserts validating getNumStoreEvents() in various cases (store / delete etc)

Improve EventStoreManager.storeEvent() speed

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTest.java

It stands to reason that if we have a public API to get DB size it should be accurate at the time of calling.  This also fixes a lot of Hybrid Tests.

Force WAL checkpoint in getDatabaseSize.

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/manager/SyncTask.java

Otherwise, calling clean sync ghost in call back when done status detected will complain that sync is still running

Removing completed syncs from active tasks before calling callback

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BriefcaseSyncDownTarget.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/JSONObjectHelper.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/BriefcaseSyncDownTargetTest.java

BEFORE
When fetching records using the ids returned by the priming records api, we currently build the SOQL query with all the ids in the where clause.
However the priming records api could return up to 50,000 ids at once, so the SOQL query could exceed its maximum length (100,000 characters) or returned results over multiple pages (which the code currently does not expect).
NOW
We chunk the ids in group of 2000 so as to not exceed SOQL query maximum length and avoid paged responses.

BriefcaseSyncDownTarget chunks up ids when getting records

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BriefcaseSyncDownTarget.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/SyncManagerTestCase.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/BriefcaseSyncDownTargetTest.java

To avoid too much memory usage.
If you have
```
typejA -> idA1 ... idAn
typeB -> idB1 ... idBn
etc
```
We are building a list that looks like `[idA1 ... idAn idB1 ... idBn ... ]`
And chunking that list, so if there are a lot of A's, we might do only A's in the first round, but if there are less than 500 A's we might do all the A's and some B's etc - but always no more than 500 records.
The new class `TypedIds` is a helper class that has methods for "chunking" and also for going back to the map of object type to list of ids.

Returning at most countIdsPerSoql records from startFetch / continueFetch

---

.circleci/config.yml
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BriefcaseSyncDownTarget.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/BriefcaseSyncDownTargetTest.java

Using sObject collection retrieve instead of instead of SOQL where ids in xxx:
* we can get 2000 records per call since sObject retrieve uses POST body and therefore avoids 414 error URI too long

Using sObject collection retrieve in BriefcaseSyncDownTarget

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/CollectionSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/CompositeRequestHelper.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
libs/test/MobileSyncTest/res/raw/usersyncs.json
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/config/SyncsConfigTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/ManagerTestCase.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/SyncManagerTestCase.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTargetTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/CollectionSyncUpTargetTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTargetTest.java

* New sync up target `CollectionSyncUpTarget` (a subclass of `BatchSyncUpTarget`, itself a subclass of `SyncUpTarget`) uses sobject collection create/update/upsert/delete instead of composite batch.
* It's the new **default** for sync up (when implementation class is not specified) replacing `BatchSyncUpTarget` (which was the default since 7.1).
* Most of the work went into refactoring `CompositeRequestHelper` to allow it to work with requests/responses to/from `composite/batch` or `composite/sobjects`, as a result `CollectionSyncUpTarget` is very short (constructors plus a one line overriding method `sendRecordRequests`).
* New test suite: `CollectionSyncUpTargetTest` (a subclass of `BatchSyncUpTargetTest`, itself a subclass of `SyncUpTargetTest`) so running the same tests as existing …

New sync up target using sobject collection

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/manager/AdvancedSyncUpTask.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BriefcaseSyncDownTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/CollectionSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncUpTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncTarget.java
libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTargetTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/CollectionSyncUpTargetTest.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTargetTest.java

During collection sync up, we no longer check records last modified date one at a time.
Instead we leverage sobject collection retrieve to get last modified date by batches of up to 2000.

Bulk checking last modified date during collection sync up

---

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/manager/CleanSyncGhostsTask.java
libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/SyncManagerTest.java

As a result, running a sync down after running a sync down would throw the "Sync is running" error.

Clean ghost tasks was never removed from active sync list

---

.circleci/config.yml

- Add API 32 and 33 (full coverage from 24-33).
- Convert triggers from deprecated Scheduled Workflows to Scheduled Pipelines, specified in "Triggers" tab of project settings on CircleCi website.  This change makes triggering tests manually though the GUI possible (and easy) against any branch.  
- Move back to Matrix workflows to avoid a few hundred lines of boilerplate. 
- Remove RestExplorer UI tests from PR runs.

Update CI 

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/config/BootConfig.java

This is the only method that is for sure going away.  It seems unlikely that methods in `PushMessages.java` will change signature based on my initial testing.

Deprecate getPushNotificationClientId.

---

.circleci/config.yml

This change will limit us to a max of API 30 for testing, but all emulators that support higher API versions are currently not working.

Workaround Firebase Test Lab device issue.  

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBHelper.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreTest.java

Before
Calling `hasSoup` would go to the db every time if the soup did not exist (it would leverage the soupNameToTableNameMap when the soup did exist).
`Now`
Now `hasSoup` avoids going to the db if the soup does not exist (and `hasSoup` was previously called for the same soup name) thanks to a new `soupNameToExistMap` in `DBHelper`.

Faster has soup when soup does not exist

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueStore.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/MemCachedKeyValueStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStoreTest.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/MemCachedKeyValueStoreTest.java

- MemCacheKeyValueStore had in map of String to String to speed up retrieval of values that only handles strings, now it is a map of String to bytes[].
- KeyValueStore and its implementation (KeyValueEncryptedFileStore and MemCacheKeyValueStore) have a contains() method.
- New tests.

MemCacheKeyValueStore can now handle binaries + new method contains on KeyValueStore

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClient.java

[WebView App Cache is gone](https://web.dev/appcache-removal/) and has been disabled on Chromium-based browsers for about a year now.  Now the deprecated methods regarding App Cache are removed in Android 13, and they have been no-ops for a while now.  This simply removes them so that targeting API 33 builds successfully.

Removes deprecated WebSettings app cache methods

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/DeleteDialogFragment.java
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/LogoutDialogFragment.java
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/LogoutDialogFragment.java

I chose to deprecate instead of just updating this now because `android.app.DialogFragment` and `androidx.fragment.app.DialogFragment` are not exactly the same; meaning some apps existing overrides could break.

Deprecate classes that extend the old DialogFragment.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AnalyticsPublisherService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SFDCRegistrationIntentService.java

I chose to deprecating entire classes because it gives us a lot of freedom with our 11.0 implementation.  Rewriting these classes altogether in Kotlin (with coroutines) looks to be a promising option.

Deprecate JobIntentService classes to migrate to WorkManager in 11.0.

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java

Using PRAGMA cipher_default_kdf_iter changes the global default value, which affects all databases opened from that point forward. This is dangerous when Mobile SDK is used in an application where any other code uses SQLCipher directly, as connections to those databases will unexpectedly have a non-default value for kdf_iter.
This change sets kdf_iter only for the specific database connection being opened. Per the SQLCipher docs, this needs to happen after the key is set (so in the postKey() hook).
Already done on iOS: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3548

Set kdf_iter for current connection, not global default

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
hybrid/HybridSampleApps/AccountEditor/build.gradle
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle
hybrid/HybridSampleApps/NoteSync/build.gradle
libs/MobileSync/build.gradle
libs/SalesforceAnalytics/build.gradle
libs/SalesforceHybrid/build.gradle
libs/SalesforceReact/build.gradle
libs/SalesforceSDK/build.gradle
libs/SmartStore/build.gradle
native/NativeSampleApps/AppConfigurator/build.gradle
native/NativeSampleApps/ConfiguredApp/build.gradle
native/NativeSampleApps/MobileSyncExplorer/build.gradle
native/NativeSampleApps/RestExplorer/build.gradle

This allows us to write Kotlin code in the SDK.  I have specified a Kotlin `apiVersion` and `languageVersion` of 1.6 so that is the _minimum_ version consumers must use.  This setting will throw errors if we use newer non-backwards compatible features within the SDK, but we are allowed to take advantage of the bugfixes and perf improvements associated with compiling against latest version of Kotlin (`1.7.21` in this case).  
~~TODO:  Catch the unhelpful error thrown by not specifying a Kotlin version in a pure Java project and re-throw with a message stating that Kotlin 1.6+ is required.~~
Edit: 
```
A problem occurred evaluating project ':libs:MobileSync'.
> Plugin with id 'org.jetbrains.kotlin.android' not found.
```
The above is the **Gradle** error that is thrown in a pure Java app. …

Add Kotlin dependency.  Bump grade version and all other dependencies.

---

libs/MobileSync/build.gradle
libs/SalesforceHybrid/build.gradle
libs/SalesforceSDK/res/values/sf__styles.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceListActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
native/NativeSampleApps/ConfiguredApp/build.gradle
native/NativeSampleApps/MobileSyncExplorer/build.gradle
native/NativeSampleApps/MobileSyncExplorer/res/layout/main.xml
native/NativeSampleApps/MobileSyncExplorer/res/menu/action_bar_menu.xml
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/DeleteDialogFragment.kt
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/DetailActivity.java
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/LogoutDialogFragment.kt
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/MainActivity.java
native/NativeSampleApps/RestExplorer/AndroidManifest.xml
native/NativeSampleApps/RestExplorer/build.gradle
native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/ServerPickerActivityTest.java

This effort migrates the final two dialogs from the deprecated `android.app.DialogFragment` to Android Jetpack's `androidx.fragment.app.DialogFragment`.  There are a couple of related migrations to `AppCompatActivity`, `RecyclerView` and new themes as well where the new dialogs needed Jetpack support.
~This is in draft status for some preview discussion.  The sample apps all build and run.  The unit tests need additional local verification.  Also, we could revert a few changes if there's any desire to and a means to run Jetpack dialogs without AppCompatActivity to support them.~
_20230505: 🚀 Ready for review!  All unit and instrumented tests pass on my workstation._
Thanks for reading! ⭐️

@W-11432310: Remove Deprecated Fragment Code

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPAuthCodeHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/DevInfoActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java

- By default it will use "web server flow".
- By calling SalesforceSDKManager.getInstance().setUseWebServerAuthentication(false), an app can opt to use the (deprecated) user agent flow instead. 
- The selected flow is shown in the dev info screen.

Login through web view can use "user agent flow" or "web server flow"

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigTask.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java

Previously if a user did a logout followed by a login, they would go straight to the allow/deny screen. 
Changes were made initially in the internal fork of the Mobile SDK (see [here](https://git.soma.salesforce.com/Android/SalesforceMobileSDK-Android-Public/pull/283)). 
There is a new property shareBrowserSession (and a method setBrowserLoginEnabled) on SalesforceSDKManager to go back to the old behavior. 
That flag can also be set through the AuthConfig.

Using prompt=login during advanced authentication so that user must re-enter credentials

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java

This is a simple bug fix to have both the app bar back and system back perform the same authorization selection action.  This corrects an earlier regression during AppCompat migration.  Thanks for catching it!

@W-13473746: [Android] Server switching not happening anymore when expected

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

This follow-up to #2414 adds an opt-in for the Salesforce integration user authentication block which defaults to `false`.

@W-13544970: [Android] [SDK Opt-In Parameter] Enable blocking of mobile app access to "salesforce integration" users in Mobile SDK

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/ClientManagerTest.java

Added helper method `fromBundleWithSafeLoginUrl` on `LoginOptions` that builds a `LoginOptions` from the provided bundle but checks the loginUrl. If it is not one of the login servers, then the selected login server is used instead.
This is to address W-11369931

Not allowing arbitrary websites in the login web view

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPAuthCodeHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java

SalesforceSDKManager has a new flag: useHybridAuthentication (defaulting to true) that causes us to use:
- when true: hybrid_token (authorization user agent flow), hybrid_auth_code (code exchange during web server flow) and hybrid_refresh (refresh flow)
- when false: token (authorization user agent flow), authorization_code (code exchange) and refresh_token (refresh flow)

Configurable authentication flow

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

🚀 _Ready for review._ ⭐️
This is an investigation into the stack track in [W-12727938](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NgIPYYA3/view) and related the related [Github Issue](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/317).  What I've seen consistently in my attempts to replicate the test is _slightly_ different.  My React Native app allows log in and out perfectly so long as the app is never paused while the login activity is displayed.  A pause can be triggered by returning to the Android launcher, for instance.
If the app is paused while the login activity is displayed, the `MainActivity` instance is destroyed which unregisters the broadcast intent receiver that login completion depends on.  On login, the app simply finishes …

@W-12727938: Crash after login if first backgrounded. Android Debug build only.

---

libs/SalesforceSDK/res/values/sf__styles.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/AccountSwitcherActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/DevInfoActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ManageSpaceActivity.java

🥁 _Ready for review_ 🎸
This updates the `SalesforceSDK` style so that our MSDK 11 updates using `AppCompatActivity` will theme exactly as they do in 10.2.0.  This applies to both light and dark modes plus all the activities in the sample apps.  Also, this ensures the theme is the same API 24 to current.
I tested this side-by-side with 10.2.0 in MobileSyncExplorer in login activity and all the other activities in the sample app.

@W-13610752: LoginActivity UI appears different in 11.0

---

libs/SalesforceSDK/res/values/sf__strings.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/SPManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/interfaces/SPManager.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/idp/IDPSPManagerTestCase.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/idp/SPManagerTest.kt

During SP initiated login flow, clicking "Login with IDP" will show a toast saying "Failed to send request to IDP app" if IDP is not installed. (Before, the SP app would crash because of the unhandled ActivityNotFoundException)

Graceful handling of non-existent IDP app

---

hybrid/HybridSampleApps/NoteSync/src/com/salesforce/samples/notesync/ContentSoqlSyncDownTarget.java
libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPAuthCodeHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java

User info is a /services/oauth2 end point, not /services/data one. It returns a 403 for an invalid access token which we don't handle automatically. See end of that [doc](https://help.salesforce.com/s/articleView?language=en_US&id=sf.remoteaccess_using_userinfo_endpoint.htm&type=5). Initially, we would refresh the access token upon getting a 401 or 403, but certain clients relied on that 403 to determinate if their token was invalid, so we had it controlled by a flag, and then we got rid of the flag but we kept using the calls to user info for our "cheap rest call" to refresh the access token.
In this PR, we are adding a wrapper for "limits" (with a test). And we are now using a call to "limits" as our "cheap rest call" (in the IDP code and in SalesforceDroidGapActivity)

Not using get user info for our "cheap rest call" to refresh access token

---

libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartSqlTest.java

Three new tests:
- non-ascii characters in string indexed field, 
- non-ascii characters in json1 indexed field, 
- non-ascii characters in non-indexed field.

New tests where we query soup elements with non-ascii characters

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/security/EncryptorTest.java

🥁 _Ready For Review_ 🎸
This replaces a few explicit references to the deprecated SHA1PRNG random number generation algorithm with APIs that allow the Android system to choose the recommended algorithm.  That should have this code compliant with the current recommendation.
I did some extra verification with both fresh installs of the app an upgrades from `dev` during log on, log out and all the unit tests.
Here's a quick compilation of related research.
👉🏻 https://android-developers.googleblog.com/2013/02/using-cryptography-to-store-credentials.html
👉🏻 https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html
👉🏻 https://developer.android.com/guide/topics/security/cryptography#kotlin

@W-12610994: [Android] Update reference to SHA1PRNG algorithm

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStoreTest.java

Running the new test with some logging and different buffer size gave the following results.
NB: the test uses a ByteArrayInputStream, performance could be even worse if reading directly from a file.
```
1 byte at a time (original code)
Reading bytes    (131072) => 5120.792 micro-seconds
Encrypting bytes (131072) => 646.958 micro-seconds
Reading bytes    (262144) => 9547.917 micro-seconds
Encrypting bytes (262144) => 820.625 micro-seconds
Reading bytes    (524288) => 19174.5 micro-seconds
Encrypting bytes (524288) => 1612.125 micro-seconds
Reading bytes    (1048576) => 37353.083 micro-seconds
Encrypting bytes (1048576) => 1702.458 micro-seconds
Reading bytes    (2097152) => 73364.916 micro-seconds
Encrypting bytes (2097152) => 3351.584 micro-seconds
Reading bytes    (4194304) => …
```

Improving key value store read performance

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java

- Opt-in regex pattern to specify domains.
- If a valid url is entered via the "Use Custom Domain" button on the login page store it in the server list.
- Open custom domain urls in Chrome (advanced auth) if appropriate.

Optionally support use custom domain button in webview.

---

libs/SalesforceSDK/res/values/sf__strings.xml
libs/SalesforceSDK/res/values/strings.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/developer/support/activities/ShowDeveloperSupportActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/developer/support/notifications/local/ShowDeveloperSupportNotifier.kt
libs/SalesforceSDK/src/debug/AndroidManifest.xml

🥁 _Ready for review!_ 🎸
This change adds a new "Show Salesforce Mobile SDK Developer Support" local notification for MSDK apps running with the debug build configuration.  The benefits hopefully include more intuitive access to the developer support dialog plus an alternative to the difficult to access shake gesture.
The shake gesture became more difficult to access since Android Emulator, as an embedded tool window of Android Studio, generally cannot receive general keyboard shortcuts.
For testing, here's some of the logic I thought of.  More ideas are welcome!
- The notification is only displayed for debug builds when developer support is enabled
-  Builds other than debug will not show the notification, regardless of developer support enablement, since the manifest will not include the …

@W-13673997: [MSDK Android] Improve Debug Menu Access In Android Emulator

---

native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/DetailActivity.java

This simply hides two options menu items in the Mobile Sync Explorer native sample app that appear to have been show in the detail activity by mistake.

@W-13924719: [MSDK Android] Native Sample Apps Have In-Operative Menu Items

---

build.gradle.kts
buildSrc/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
hybrid/HybridSampleApps/AccountEditor/build.gradle.kts
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts
libs/MobileSync/build.gradle.kts
libs/SalesforceAnalytics/build.gradle.kts
libs/SalesforceHybrid/build.gradle.kts
libs/SalesforceReact/build.gradle.kts
libs/SalesforceSDK/build.gradle.kts
libs/SmartStore/build.gradle.kts
native/NativeSampleApps/AppConfigurator/build.gradle.kts
native/NativeSampleApps/ConfiguredApp/build.gradle.kts
native/NativeSampleApps/MobileSyncExplorer/build.gradle.kts
native/NativeSampleApps/RestExplorer/build.gradle.kts

This prepares `SalesforceMobileSDK-Templates` for most of its Gradle Groovy DSL to be converted to Kotlin DSL.  See its [companion pull request](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/372/files).
Unfortunately, it wasn't possible to coerce React Native nor its community libraries to integrate with Gradle 8 and the Android Gradle Plugin 8, so this rolls that back to 7 here.  The two repositories must remain in sync since they are a composite build.
React Native will be moving to Gradle 8 in the near future, though the timing of community library updates is less clear.
In the end, all the Groovy DSL that is not derived from React Native templates can be migrated to Kotlin DSL, so a large body of work is still possible.  Yay!
All of the …

@W-14149830: [MSDK Android] Convert Template Apps To Gradle Kotlin DSL

---

hybrid/HybridSampleApps/MobileSyncExplorerHybrid/AndroidManifest.xml
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/res/values-v34/system_back.xml
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/res/values/system_back.xml
libs/SalesforceHybrid/AndroidManifest.xml
libs/SalesforceReact/AndroidManifest.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ScreenLockActivity.java
native/NativeSampleApps/MobileSyncExplorer/AndroidManifest.xml

I tried to implement this about a year ago when it was first announced.  At that time, users could opt-in via a setting in the developer options of their API 33 (Android 13) device and enable it with a manifest option to test their apps, but the feature wouldn't be forced on for all apps until API 34 (Android 14).  I was able to work around the issue it caused for our Screen Lock (a.k.a passcode) feature but not the lack of support from Cordova and React Native.  Because in app back navigation completely broke for those skews we deferred support until API 34.  
Since then, Google has changed the strategy somewhat.  As of the last Android 14 beta the visual impact of the feature still cannot be seen without the user opting in through developer options (maybe it will be in the final release …

Support Predictive System Back.

---

settings.gradle.kts

⭐️ _Ready for review_ 💫
This resolves an issue where MSDK, when building as a composite build of the template apps, cannot resolve the React Native local Maven repository that is provided by the template.  The template doesn't populate the RN install in `libs` that MSDK itself expects.  MSDK and the template apps install RN to different paths, so this adds a reference to each.  The build safely ignores any repository that is not present.
As a composite build, MSDK and the app enjoy some isolation from each other's build configuration and consistency when building either stand-alone or together.  That's good in the long run plus provides something of a single-source-of-truth when it comes to build expectations.  The only drawback, and probably it's good for build consistency, is that they …

@W-14213012: [Android][ReactNative] forcereact generated applications are broken

---

hybrid/HybridSampleApps/AccountEditor/build.gradle.kts
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityDelegate.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/LogoutCompleteReceiver.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/UserSwitchReceiver.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java
native/NativeSampleApps/AppConfigurator/build.gradle.kts
native/NativeSampleApps/ConfiguredApp/build.gradle.kts
native/NativeSampleApps/MobileSyncExplorer/build.gradle.kts
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/MainActivity.java
native/NativeSampleApps/RestExplorer/build.gradle.kts

Apps targeting API 34 are **required** to specify export behavior for all broadcast receivers; failing to do so causes a runtime exception.  
-   Using `ContextCompat.registerReceiver`, just like Eric did for the Dev Support notification, because it prevents having to write if build version > 33 each time which still leaves a warning for the < 33 case.
- All broadcast use cases (login server, switch user, logout, cleanup, etc) work without being exported, which is a security win for API 33+.
- Bump sample apps (but not libraries) in repo to API 34 to ensure we don't miss other issues like this.

Specify export behavior for broadcast receivers.

---

.circleci/config.yml
settings.gradle.kts

🥁 _Ready For Review_ 🎸
This is a companion to https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/626
The update here allows the MSDK Gradle workspace to build even when the React Native local repository is not present.  That is the case when MSDK is a composite build with the hybrid template apps.  A warning is printed to indicate this is the case.

@W-14246983: [Android][Hybrid] Hybrid Templates Use Maven Central MSDK Dependencies By Default

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/MainActivity.java

This resolves the native MobileSyncExplorer sample app's inability to display contacts on API 34 devices.  Turns out this had to do with how broadcast receivers are exported for use by `LoaderManager` on API 34 compared to previous versions.  The intent is started from another process, so to preserve the behavior as it was on previous API versions, `EXPORTED` is the option that's required.

@W-14252627: MobileSyncExplorer does not display contacts for API 34

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/loaders/ContactListLoader.java
native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/MainActivity.java

See https://developer.android.com/about/versions/14/behavior-changes-14#safer-intents
Other receiver (logout, user switch, cleanup) were already invoked with explicit intents

Android 14 requires non-exported receiver to be invoked with explicit intents

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java

Keep an reference to the builder locally so interceptors added by consuming Apps are retained during the creation of RestClient.

Add ability to attach OkHttp Interceptors by consuming App

---

build.gradle.kts
buildSrc/build.gradle.kts
gradle.properties
hybrid/HybridSampleApps/AccountEditor/build.gradle.kts
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts
libs/MobileSync/build.gradle.kts
libs/SalesforceAnalytics/build.gradle.kts
libs/SalesforceHybrid/build.gradle.kts
libs/SalesforceReact/build.gradle.kts
libs/SalesforceSDK/build.gradle.kts
libs/SmartStore/build.gradle.kts
native/NativeSampleApps/AppConfigurator/build.gradle.kts
native/NativeSampleApps/ConfiguredApp/build.gradle.kts
native/NativeSampleApps/RestExplorer/build.gradle.kts

- **compileSdk to `34`**
- **Kotlin to `1.9.20`**
- Kotlin Standard Lib to `1.8.22` (`1.9+` throws an error below Gradle 8.1)
- core-ktx 
- webkit
- splashscreenn
- browser
- material
- lifecycle viewmodel
I left our Kotlin language and API versions (what we code to/our customers minimum version) at `1.6`.  [Here is what we could utilize if we bumped it to 1.7](https://kotlinlang.org/docs/whatsnew17.html).  `1.9` removes support for `1.3` (which was deprecated in `1.6`) and I don't think `1.4` is even deprecated yet so I don't see anything pressing.

Bump versions of all dependencies.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt

This resolves an incorrect use the main Kotlin coroutine dispatcher, which was the root cause of the crash reported in the work item.  There were a handful of `AsyncTask` instances replaced in a recent commit which explicitly ran on the main thread in Java concurrency, however this migration to Kotlin Coroutines wasn't intended to be one of them.

@W-14927360: Exception causes IDP flow to fail.

---

libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncTestCase.java

API 59 (unlike API 55) does not accept ":" in the referenceId: Provided referenceId ('%s') must start with a letter or a number, and it can contain only letters, numbers and underscores ('_').

Fix for ParentChildrenSyncTests

---

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushNotificationDecryptor.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManagerTest.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/KeyStoreWrapperTest.java

- encrypt and decrypt method use new cipher but try old cipher in case of failure
- key generation code had to be tweaked (to support different digest and encryption padding)
- had issue with default provider so using AndroidKeyStoreBCWorkaround for new cipher
- Added test

Using new cipher for RSA (but trying with old cipher in case of failure)

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java

Matching the [fields pulled on iOS](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Identity/SFIdentityData.h).
NB: There are a few more not pulled on either platform.

IdServiceResponse now pulls same fields than iOS

---

libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/build.gradle.kts
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/AccountSwitcherActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java

This makes the following no longer letterboxed:
- LoginActivity
- ServerPickerActivity
- AccountSwitcherActivity
ScreenLockActivity did not need the fix.  I did not check IDP activities.

Basic support for Foldable/Large screens.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/BiometricAuthenticationManager.kt

This guards for a reported null pointer crash in the biometric authentication manager.  Though, it does not solve for why an Android `Account` exists that a `UserAccount` cannot be derived from.  Potentially, more research would be needed in  `UserAccountManager.buildUserAccount(Account)` to identify the gap or to gather metrics related to the actual `Account` data at runtime.  The immediate goal is to reduce the impact of the observed crashes and improve the user experience. Here's a follow-up work item for that effort: [W-15381271: -MSDK Android- Android Account Is Sometimes Null In BiometricAuthenticationManager shouldLock
](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001nRqC3YAK/view)

@W-14831222: [Android] NullPointerException: userAccount must not be null on app foreground with biometrics

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java

This singular variable has always controlled too many distinct scenarios:
- If the webview or custom tab should reload when the app returns from the background.
- If the webview or custom tab should reload when we transition from the ServerPicker to LoginActivity.
- If `Intent.FLAG_ACTIVITY_NO_HISTORY` should be set on the custom tab activity.
This leads to bad scenarios like: you need to _not_ reload on background for MFA so you sacrifice the correct server being loaded from the picker when you switch.  <- That sucks.
**I believe all of these scenarios only have one real correct choice and it is to **not reload** ever, unless the server changes.  If a reload is needed for some extreme case we cannot foresee the manual option remains.**
[This is the PR that originally added …

Remove shouldReloadPage

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java

Because of the new `CLEAR_TOP` flag we should explicitly use the Webview Login Activity Class when switching servers to avoid accidentally dismissing the webview activity.
I was tempted to convert `ServerPickerActivity` to Kotlin instead of making `webviewLoginActivityClass` public as it isn't much work.  However, customers can extend `ServerPickerActivity` and since a lot of it is Java public or protected we would need to carefully consider the external interface before and after.  I think it makes more sense to evaluate what the interface should be (which has not been done for may years), make deprecations if necessary and convert it in 13.0.

Fix server picker issues with native login fallback to web based auth.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt

🎸 _Ready For Review!_ 🥁
This removes file URL access from the login web view to comply with the security goal of this work item.  This was discussed among the team today and there doesn't seem to be a known reason for why this is enabled.  The login use cases I tried today all seem to function just as well without this option.  If anyone has login edge cases that might have been affected, do let me know and I'll investigate.  
Thanks!

@W-14893505: [ASA Program] [#SA-01][Android] App Enables Dangerous File Access via setAllowFileAccessFromFileURLs

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java

This resolves what looks like an easy-to-fix crash when returning to login from the server picker.  The crash is due to `startActivity` being called on a `Context` reference that isn't always an `Activity` instance.  Since the method is already `ServerPickerActivity`, calling `startActivity` on `this` seems like it'd do just what the exception is asking for.
@brandonpage - Does this align with the comment in this method?

@W-15547113: [MSDK Android] Crash When Returning To Login View From Server Picker View

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/app/PublicOverrideTests.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/PublicOverridesTest.kt

Classes covered:
- SalesforceSDKManager
- SalesforceDroidGapActivity
- LoginActivity
- OAuthWebviewHelper

Fix protected functions not being open in classes recently converted to Kotlin.

---

external/cordova/cordova.js

The cordova.js in the android repo is only used by our hybrid tests.
We have not updated the file since cordova-android 11.0.0 (now we are at cordova-android 12.0.1).
Fortunately, nothing changed in that file except the version number.

Using cordova.js from cordova-android 12.0.1

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/interfaces/NativeLoginManager.kt

Here MSDK acquires the headless forgot password flow from the Salesforce Identity API.
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_headless_forgot_password_flow.htm&type=5
This follows the style we used for login and password-less login in 12.0.  Most of the new code should look quite familiar with the subtle exception of some new utility methods to keep reused logic from becoming redundant.

@W-15061223: [Android] Add additional native login feature: forgot password

---

libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java

`https://powerofus.force.com` appears to not exist anymore, which breaks a few of our tests.  We can use `https://powerofus.salesforce.com` and our own `https://mobilesdk.my.salesforce.com` to fill in the gaps.

Fix Auth Config tests.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ManageSpaceActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityDelegate.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ScreenLockActivity.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountManagerTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/NativeLoginManagerTest.kt
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/LogoutDialogFragment.java

I have elected not to add support for passing the logout reason from hybrid or React Native apps because the audience for this change is internal apps and none of them use those libraries anymore.

Add Logout Reason to Revoke API call.

---

.circleci/config.yml
native/NativeSampleApps/test/RestExplorerTest/AndroidManifest.xml

This is needed so that PR's have a baseline in `dev` to compare against.

Run CodeCov on all test runs.

---

.circleci/config.yml
build.gradle.kts
libs/MobileSync/build.gradle.kts
libs/SalesforceAnalytics/build.gradle.kts
libs/SalesforceHybrid/build.gradle.kts
libs/SalesforceReact/build.gradle.kts
libs/SalesforceSDK/build.gradle.kts
libs/SmartStore/build.gradle.kts

Apparently [CodeCov no longer supports .ec files](https://docs.codecov.com/docs/supported-report-formats), which is the only thing we can generate in Firebase Test Cloud.  So I wrote a gradle task to convert the unsupported format to XML CodeCov can process (and html we can read) with JoCoCo.

Convert Firebase Test Lab code coverage for CodeCov.

---

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java
libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java

It was not always like that - but that change of behavior means some of the bridge method might not work if an optional argument is not provided. I noticed the issue because testRemoveFromSoup started failing.

ReactNativeMap.isNull throws if the provided key is not in the map

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AnalyticsPublishingWorker.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/RestExplorerApp.java

🎸 _Ready For Review!_ 🥁
Note: This also includes [W-15993636](https://gus.lightning.force.com/a07EE00001uKF3pYAG) since the two topics look so similar in the code and test well together.
This changes MSDK to avoid resuming the app for background tasks that could incur additional authorization refresh events.  The default behavior is now to perform those tasks when the app resumes or pauses (foreground or background).  Configuration options are provided so app can opt-in to the old behavior, if desired.
I was able to test the apps to verify the new AILTN publishing in each configuration.  Also, I was able to test push notifications registration according to each configuration.

@W-15993541/W-15993636: [Android] Publish AILTN logs on background/Register push notifications on foreground

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt

Yesterday on an [iOS PR](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3741) I proudly proclaimed that we didn't need the same fix on Android because it was implemented years ago.  Which _was_ true.  However, in linking the Android code as proof I noticed that it had been broken slightly by a Kotlin conversion; this PR rectifies that.

Fix auth config fetch.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt

🎸 _Ready For Review!_ 🥁
This simple and low risk bug fix simply moves the password parameter in start user registration to where the Salesforce Identity API expects (now) according to the documentation.
I've tested this using the AndroidNativeLoginTemplate and ensured the user's new password works as expected after registration.

W-16498231: [MSDK Android] Native User Registration No Longer Sets User's Initial Password

---

publish/publish-root.gradle

The changes here aren't strictly necessary (just variable renaming) but they make the new inputs more clear. 
Maven Central has switched from allowing publishing with user credentials to a token only so we need to update our process.  I will update he doc to reflect this and the new variable names.

Update Maven Central publish script to use token instead of user credentials.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPAuthCodeHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestRequestTest.java

- Added `RestRequest.getRequestForSingleAccess` (with new tests in `RestClientTest` and `RestRequestTest`) which calls `/services/oauth2/singleaccess` to generate a frontdoor URL to bridge into UI sessions.
- Added `shouldRefresh` method in `RestClient.OAuthRefreshInterceptor`: it now refreshes when getting either a 401 or a 403 with reason `Bad_OAuth_Token` while going to `/services/oauth2` (as long as the biometric is not enabled and locked).
- Using `getRequestForSingleAccess` in `IDPAuthCodeHelper` instead of building 
a frontdoor URL directly - tested the IDP/SP flows manually (including the case where the access token has expired).
NB: Left `SalesforceDroidGapActivity.getFronDoorUrl` - we will address it in a separate PR by using the cookies returned by the hybrid authentication …

Using Single Access API to get front door URL

---

hybrid/HybridSampleApps/AccountEditor/AndroidManifest.xml
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/AndroidManifest.xml
libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
native/NativeSampleApps/ConfiguredApp/AndroidManifest.xml
native/NativeSampleApps/RestExplorer/AndroidManifest.xml

Issues covered here:
- Failed PKCE Login due to the code verifier being replaced mid flow.  
- Fixed by now allowing the webview to reload in LoginActivity `onNewIntent` while we are using advanced auth.
- If you switch servers the LoginActivity can appear again instead of the app after a successful login.
- Partly fixed by the above restriction of reloading the webview (which checks the well known config and launches the login view again when it is done).
- Partly fixed by switching the LoginActivity from `SingleTop` to `SingleTask`.  I really didn't want to do this because it is **technically a breaking chance** for consuming apps, but the LoginActivity randomly restarts after finish.  I think this is an Android bug we can't work around.  
- Advanced Auth login using the custom domain …

Fix advanced auth login issue after switching servers and other issues.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ScreenLockActivity.java

I appears we simply missed this when we converted `SalesforceSDKManager` to Koltin in 12.0.

Make SalesforceSDKManager's ScreenLockManager getter public.

---

libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt

In #2545 I made a change to delay push deregister until the device had network connection so that the operation would succeed (eventually) even if the user chose to logout while offline.  At the time of testing this worked correctly in all cases but since a change has been made that causes an error on deregister (likely the recent bugfix #2607, which retained the tokens after logout).  The error doesn't actually cause the unregister operation to fail and is invisible to the end user, but an internal team ran into issues with automated testing because of it.

Fix push deregister error.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
native/NativeSampleApps/RestExplorer/AndroidManifest.xml

This PR covers supporting Android 15 devices **prior to apps updating to API 35**.  I will follow up with a Part 2 that fixes issues and makes necessary improvements for apps targeting API 35.
Changes:
- Fixed endless advanced auth loop is no browser exits.
- This isn't specific to Android 15 pre se, but a user is significantly more likely to run into this scenario in the new [Private Space](https://source.android.com/docs/security/features/private-space) profile.
-  Update [Predictive System Back](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture) behavior.  
- "Predictable" for the OS really means that the app doesn't control it anymore.  I have basically moved all of necessary cleanup work to `onDestroy` so that it happens no matter what.
- The only …

Android 15 Support - Part 1

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.kt
libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClientHelper.java
libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewCookieManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivity.java

- based on SApp's `BridgeCookieManager`
- Gets SIDs from the `UserAccount` and sets them in the `CookieManager`
- it no longer uses front-door to load remote app
- it calls `SalesforceWebviewCookieManager`'s `setCookies` method when receiving a refresh broadcast
- cleaned up the `reload` logic (previously called `refresh` but that name was a bit confusing)
Created two apps on Mobile SDK cs4.com test org
- `apex/AccountEditor` which is the AccountEditor uploaded as hybrid remote app: it uses Mobile SDK Cordova plugins to do network operations
- `apex/AccountList` which is a true Visual Force app that shows a list of accounts and allow navigation to their detail screen
- login to hybrid remote app pointing to `apex/AccountEditor`
- do some operations (that talk to the server)
- from a …

Setting cookies on hybrid remote webview instead of loading page through front door

---

build.gradle.kts
buildSrc/build.gradle.kts
hybrid/HybridSampleApps/AccountEditor/build.gradle.kts
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts
libs/SalesforceSDK/res/drawable/sf__fix_status_bar.xml
libs/SalesforceSDK/res/layout/sf__dev_info.xml
libs/SalesforceSDK/res/layout/sf__server_picker.xml
libs/SalesforceSDK/res/values/sf__styles.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/AccountSwitcherActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/DevInfoActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/EdgeToEdgeUtil.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ManageSpaceActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ScreenLockActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
native/NativeSampleApps/AppConfigurator/build.gradle.kts
native/NativeSampleApps/ConfiguredApp/build.gradle.kts
native/NativeSampleApps/RestExplorer/build.gradle.kts

- Bumped compileSdk and targetSdk of sample apps to 35 and Gradle to 8.6.1 to match.
- Fixed an issue related to new intent rules in Android 15 that broke IDP initiated IDP flow.
- Enabled [Edge to Edge](https://developer.android.com/develop/ui/views/layout/edge-to-edge) UI for ScreenLockActivity and fixed the status bar icon color in dark mode.
- Conditionally (if app targets API 35+) enabled Edge to Edge for all other screens.  Fixed layouts taking the entire screen and showing behind status and navigation bars.  Fixed status and navigation bar colors for all screens.

Android 15 support 

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

This LogoutReason basically does not matter since it will never make it back to the server but it should still match iOS.

Rename token_expired LogoutReason to refresh_token_expired.

---

libs/SalesforceSDK/res/drawable/sf__fix_status_bar.xml
libs/SalesforceSDK/res/values/sf__colors.xml

`sf__api_35_status_bar_color` defaults to Salesforce blue but can be overridden by the app (without affecting any other UI elements):

Add new color key for Android 15 status bar.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivity.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityInterface.java

When preparing the documentation for QR code log in on iOS, I noticed Android's implementation was more probably more different than required.  So, this brings a large portion of the documentation for the two in line.
Also, Android still had one more bug where the deep link intent to main activity could be triggered again when returning to the activity.   That is fixed now.

@W-16814802: [iOS] Add Deep Link From External QR Code Reader To iOS Native Swift Template QR Code Login (Parity For Android)

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AnalyticsPublishingWorker.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt

🤘🏻 _*Ready For Review!*_ 🎸
This simple Trust update ensures the Android Background Tasks library will not be used to create duplicate work.

@W-16797266: [TRUST] Ensure all WorkManager Jobs have an associated tag or unique name

---

hybrid/HybridSampleApps/AccountEditor/build.gradle.kts
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
native/NativeSampleApps/AppConfigurator/AndroidManifest.xml
native/NativeSampleApps/ConfiguredApp/AndroidManifest.xml
native/NativeSampleApps/ConfiguredApp/src/com/salesforce/samples/configuredapp/ui/MainActivity.java
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/ExplorerActivity.java
native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/ServerPickerActivityTest.java

- Fixed Server Picker UI tests.
- Downgraded hybrid test apps to API 34 to avoid Edge to Edge issues.
- Fixed Edge to Edge issues on native test apps.
- Fixed a couple AndroidManifest issues with test apps.

Test and Test App Cleanup

---

libs/SalesforceAnalytics/build.gradle.kts
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/SalesforceLogReceiver.kt
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/SalesforceLogReceiverFactory.kt
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/SalesforceLogger.java

This adds a new concept of "log receivers" to the SDK's existing logging infrastructure, plus a "factory" which can be registered by the app to create and register these receivers to named components in the logging flow.  The factory object could be a bridge to the app's dependency injection framework, such as Hilt.
I tried this out in the template apps and the overall pattern gave the app what I expected.  I marked this ready for review with the anticipation we might have to discuss the naming convention a bit.  I thought over names such as "adapter", "destination", "target" or "handler" before settling on "receiver". I though this was a good semantic since the object only has to "receive" the log entry - What happens after that is entirely up to the …

@W-16580498: [Android] Hook to propagate MSDK logs to other systems

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt

This updates a deprecation for the `OnLifecycleEvent` code generation annotation in `SalesforceSDKManager`.  It turns out the fix was pretty simple since `SalesforceSDKManager` already registered as a `ProcessLifecycleOwner` observer.  It just needed to implement one of the `LifecycleObserver` sub-interfaces, such as `DefaultLifecycleObserver`, so the two existing lifecycle-related methods could be called without the deprecated code generation.
I tested this on API 35 and compared how the two lifecycle methods are called in comparison to the previous version.  It certainly seems on par.

@W-17051459: [TRUST] Improve Android Lifecycle events/actions

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/Features.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt

This one follows along with recent changes to add a feature code for Native Login in #2637.

@W-17291582: [Android] [Instrumentation] Add QR Code feature logging to track adoption

---

.circleci/config.yml
gradle.properties
hybrid/HybridSampleApps/AccountEditor/build.gradle.kts
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts
libs/MobileSync/build.gradle.kts
libs/SalesforceAnalytics/build.gradle.kts
libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
libs/SalesforceHybrid/build.gradle.kts
libs/SalesforceReact/build.gradle.kts
libs/SalesforceSDK/AndroidManifest.xml
libs/SalesforceSDK/build.gradle.kts
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java
libs/SmartStore/build.gradle.kts
native/NativeSampleApps/AppConfigurator/build.gradle.kts
native/NativeSampleApps/ConfiguredApp/build.gradle.kts
native/NativeSampleApps/RestExplorer/build.gradle.kts

Changes:
- Changed minSdk from 26 to 28
- Removed checks for 28/Android.P in code
- No longer using BC provider (see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html)
NB: Also updated GUI driven [triggers](https://app.circleci.com/settings/project/github/forcedotcom/SalesforceMobileSDK-Android/triggers) on Circle CI (removed 26, 27 and added 35)

Changing min sdk from 26 to 28

---

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java

Needed in order to use commercial or enterprise editions of SQLCipher.
- Put the aar for SQLCipher commercial or enterprise edition in the `libs/SmartStore` folder.
- Change `libs/SmartStore/build.gradle.kts`
- Replace dependency for SQLCipher e.g.
```
-    api("net.zetetic:sqlcipher-android:4.6.1")
+    api(files("sqlcipher-android-fips-4.6.1.aar"))
```
- Add to packaging
```
jniLibs {
keepDebugSymbols += setOf("*/*/libfips.so", "*/*/libfipscnf.so")
useLegacyPackaging = true
}
```
- Change `libs/test/SmartStoreTest/src/com/salesforce/androidsdk/TestForceApp.java`
- Add the following to `onCreate()` before everything else
```
SmartStore.setLicenseKey("--YOUR-SQLCIPHER-LICENSE-KEY--")
```
Only the testSQLCipherVersion should fail, it will report the SQLCipher edition you are using instead …

Add ability to provide SQLCipher license key

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java

NB: Falling back on PKCS1 at decryption time to successfully decode unique id encoded with MSDK 12 or older
At this point PKCS1 is only used in fall back scenarios - to decrypt payloads encrypted for older version of MSDK:
- to decrypt encrypted push notifications, if server generated key was created with PKCS1 cipher mode
- to decrypt unique id, if it was encrypted with PKCS1 cipher mode

Using OAEP cipher mode to encrypt unique id

---

.github/workflows/nightly.yaml
.github/workflows/pr.yaml
.github/workflows/reusable-workflow.yaml

This PR adds a `is_pr` input parameter to our reusable-workflow.  The value of `github.event_name` changes from `pull_request` (or however the original flow started) to `workflow_call` in the reusale-workflow since that is technically how the _reusable-workflow was triggered_.  
CI will fail because it runs the workflow file on `dev`.  Tested [here](https://github.com/brandonpage/SalesforceMobileSDK-iOS/pull/13).

Fix Github Actions PR event checks.

---

.github/workflows/nightly.yaml
.github/workflows/reusable-workflow.yaml

This PR changes the Nightly test structure from running one Firebase Test Lab with all supported API levels simultaneously to running them sequentially.  
If we try to run 8 instances (API 28 to 35) of our tests at once, matrixes across all of our libraries, it is simply too many simultaneous API calls to the server and the tokens gets invalidated.  This also probably would have lead to a lot of flapping tests in MobileSync when manipulating data on the server.  
Here is an example of the report from a test I ran with just 28 and 35:
In production it will show all (8 as of now) supported API levels in a single report page per library:

Fix nightly test runs.

---

.github/workflows/nightly.yaml
.github/workflows/reusable-workflow.yaml

Other improvements:
- Fixed Code Coverage reporting.
- Use of two different Test Reporters (for now?):
- One for PRs:  This action understands and correctly reports "flaky" tests and tests that Firebase has re-run.  But it does not display multiple test runs well (stating 2k+ tests ran and 1 failed does not tell me which API version it failed on).  I have opened an issue asking for multi file support.
- One for Nightlies: This action displays test results per file, so it is easy to tell what API levels tests pass or fail on.  Reports tests that fail at first and succeed on the re-run as failures.  I have commented on the issue asking for flaky/re-run support.
-  Increased the number of re-run attempts for PRs to 2 and decreased it to 0 for nightly runs (largely due to reporters).

Restructure Nightly jobs to prevent flappers.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java

That inner class should have been removed when we did https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2203

Removing unused code

---

libs/SalesforceSDK/res/values/sf__strings.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LoginServerManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginServerListItem.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/PickerBottomSheet.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/LoginViewModelTest.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/ui/LoginViewActivityTest.kt

LoginViewModel Customization (and cleanup)

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt

Recently we made a change to not show the BottomAppBar at all if there was no button to display in an effort to increase the amount of webview shown (especially for landscape).  However, this causes the problem of not setting a color for the nav bar because we are not displaying anything there.  This isn't very noticeable with the default login background (in light mode) but other background colors make it very obvious.  For example this is what the default login screen looks like in dark mode:
This PR fixes this and the original issue by always displaying the BottomAppBar and adjusting it's height based on whether or not we are showing a button.  The appearance when showing a button is unchanged, but the color and height are fixed when there is no button:

Fix LoginView nav bar when button is not shown.

---

.github/workflows/reusable-workflow.yaml

I worked with the owner of the `action-junit-report` action to get support for un-grouped test reports so we can visualize test reporting _per API level_.  
Previously it would group all reports together like this:
Now, we will get a table more like this:

Improve Github Actions Test Reporting.

---

libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/ManagerTestCase.java

🎸 *_Ready For Review_* 🥁
This gets the tests compiling again, but I do notice some test failures for both 12.x and 13.x in the suite that look like this.  If I recall, I always used to get these when testing against MobileSDK.
```
Wrong total size expected:<4> but was:<0>
```

@W-17920337: [MSDK Android] `MobileSyncTest` Test Suite Fails Due To Removal Of Login Options

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsApiClient.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsTypesResponseBody.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/PushMessagingTest.kt

🎸 *_Ready For Review_* 🤘🏻
This adds support for fetching, storing, retrieving and clearing the new Salesforce push notifications types on SFDC registration and unregistration.

@W-17459651: Actionable Notifications (Android) Support For Notifications Types

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt

🤘🏻 *_Ready For Review_* 🎸
This relatively simple update registers Android Notification Channels for each Salesforce Notification Type on log in.  They're then removed at log out.  They new channels are also added to an Android Notification Group.

@W-18033420: Actionable Notifications (Android) Register/De-Register Android Notification Channels For Notifications Types

---

.codecov.yml

- Add `threshold: 0%` to all libraries.  This will fail a check if a PR lowers the overall coverage of a library by any amount. 
- Add new `patch` section with `target: 80%` for each library.  This will create a check per library that will ensures new code added in a PR has at least 80% coverage.  
I could have required a specific coverage amount (like 80%) per library but most are no where near where we ideally want them.  Instead, these rules should encourage us to organically work towards that goal.

Update CodeCov requirements.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt

This is a followup to #2703, which insured the status bar icons were always visible for any dynamic status bar color.  However, it did not take into account that the app can specify a static top app bar color.

Fix status bar icon color for all cases.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountBuilder.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticatorService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountTest.java

- Saving beacon child consumer key and secret in user account when returned in token end point response
- Using beacon child consumer key instead of configured consumer key if available
- Updated tests
- Tested manually with beacon app setup in test environment (na54)

Beacon support

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticationUtilities.kt

This fixes the issue of the current user not being set correctly when we notify the app of the user switch.

Switch to new user before sending user switch intent.

---

libs/SalesforceSDK/AndroidManifest.xml

This resolves the [Github issue](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/409#issue-3027790487) which was linked in the work item where MSDK's Android manifest orientation restrictions were causing publishing warnings for apps.  The simple solution appears to be simply removing the restriction since the activity lays out and performs the same in all orientations and has a very simple layout.
Is there more context to this issue?
According to our discussion today, I shelved all the other available "Android 16" updates for future work, if that's OK.  There's plenty of code and troubleshooting there that's already done, at least.

@W-17459669: Android 16 support

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountBuilder.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticatorService.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/test/TestCredentials.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountTest.java
native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/ExplorerActivity.java

- token end point response contains api_instance_url (when sfap_api scope is being used)
- this value is now captured and saved in the user account
- tests were updated
- test_credentials.json exported by RestExplorer and used in tests now includes api instance server
TBD?: passing this value to SfapApiClient directly

Saving API instance URL in user account

---

build.gradle.kts
buildSrc/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
hybrid/HybridSampleApps/AccountEditor/build.gradle.kts
hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts
libs/MobileSync/build.gradle.kts
libs/SalesforceAnalytics/build.gradle.kts
libs/SalesforceHybrid/build.gradle.kts
libs/SalesforceReact/build.gradle.kts
libs/SalesforceSDK/build.gradle.kts
libs/SmartStore/build.gradle.kts
native/NativeSampleApps/AppConfigurator/build.gradle.kts
native/NativeSampleApps/ConfiguredApp/build.gradle.kts
native/NativeSampleApps/RestExplorer/build.gradle.kts

This updates MSDK Android to the latest Gradle and Android Gradle Plugin plus a few other dependency updates.  However, it doesn't take the next two steps of updating to Kotlin 2 and the Kotlin Compose Compiler Gradle Plugin or Android API 36.
Note: There are two really valuable "future" commits on this branch history that actually have working code for the two deferred steps.  We can cherry pick those in when the time comes for some serious effort reduction since that's completed.

@W-18648586: Gradle upgrade

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/AppLockManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/BiometricAuthenticationManager.kt

Stack Trace:
Fatal Exception: java.lang.NullPointerException:
at com.salesforce.androidsdk.security.BiometricAuthenticationManager.isEnabled(BiometricAuthenticationManager.kt:44)
at com.salesforce.androidsdk.security.BiometricAuthenticationManager.shouldAllowRefresh(BiometricAuthenticationManager.kt:94)
at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.shouldRefresh(RestClient.java:703)
at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:718)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
at …

Fix rare race condition crash.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java

Manually tested by:
- stepping through debugger on the client
- watching the session management page in the browser at the same time to see the oauth2 session disappear

Revoke refresh token with a HTTP POST instead of a HTTP GET call

---

libs/SalesforceSDK/res/xml/servers.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LoginServerManager.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
native/NativeSampleApps/RestExplorer/res/xml/servers.xml

`LoginActivity` is updated to support selecting Salesforce Welcome Discovery URLs plus responding to their callback URL to initiate log in.
During the discussion in Slack with @wmathurin and @Crebs, we leaned towards having WSC behave and look as much like the existing default login activity as possible.  In particular, app bar and overflow menu are identical.  With that in mind, it was really easy to fold the new logic into our existing activity.
Here's a video that shows the new login/welcome flow in action.  This updated version of the video today shows the more polished version.
[Screen_recording_20250721_140629.webm](https://github.com/user-attachments/assets/f8bacb22-9a85-4e3b-a2bb-30c7b9107bd2)

@W-17964655: [Android] WSC discovery endpoint to postpone OAuth flow

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt

This provides two bug fixes for QR Code Log In.
One, it corrects the `useWebServerFlow` property so that the presence of the front-door bridge URL drives the logic and its associated code verifier determines between Web Server and User-Agent Flow.  The app's two properties are used as they always have been only if there's no in-flight QR Code Log In.
Second, it updates `LoginActivity` so that `onNewIntent` can receive a QR Code Log In URL just as it now does for Salesforce Welcome Discovery URLs.  The logic that was fixed in `onCreate` for QR Code Log In is now tidy in their own methods.
This has been tested by Tao He in the `main` branch of SApp.

@W-19100006: [Android] QR code login not working with webserver flow disabled

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt

This was not a problem for our UIAutomator2 tests, but teams using Appium's web context could potentially experience issues switching context prior to this change.  This is Chrome inspector:

Instantiate login webview by lazy to ensure only one is ever created.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt

This pretty important for the deferred login scenario, but not critical since it does not affect the devices back button/gesture.  
Despite this being a one line change I thought quite a big about the making the value `open` vs changing it to `var`. Ultimately, it comes down to steering the app to interact with the SDK in the most desirable way.  Making it open means they need to extend our ViewModel to define the value.  IMO this is a far better alternative to setting the value on our ViewModel since it would have to be done from a class that extends `LoginActivity`.  
Edit:  I have also improved the back logic so an app that defines `shouldShowBackButton` does not also need to extend LoginActivity to override `fixBackButtonBehavior` for older devices.  
Perhaps `fixBackButtonBehavior` …

Make shouldShowBackButton value open.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/KeyStoreWrapperTest.java

**Issue:**
After upgrading from SDK V11 to V13, users were unexpectedly logged out when restarting the app a second time. The failure sequence was:
1. **V11 behavior**: Stored unique ID encrypted with PKCS1 using PKCS1-only keys
2. **V13 first run after upgrade**:
- Attempts OAEP decryption (fails - stored with PKCS1)
- Falls back to PKCS1 decryption (succeeds - gets unique ID)
- Attempts to re-encrypt and store with OAEP for future use
- OAEP encryption fails silently because V11 keys don't support OAEP padding
3. **V13 second run** (app restart):
- Attempts OAEP decryption (fails - OAEP storage failed in step 2)
- Falls back to PKCS1 decryption (fails - old PKCS1 version overwritten)
- Unique ID becomes unreadable → refresh tokens can't be decrypted → user logout
**Root Cause:**
V13's …

Fix user logout issue during V11→V13 app upgrades caused by failed OAEP re-encryption

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManagerTest.kt

Without this, an application will not be able to decrypt encrypted push notifications if:
- it was first installed with Mobile SDK 11.x or older
- **it has elected to disable re-registration entirely** by changing https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/e435f54e8359c8399edd94d65e2fe3d54dfb2d60/libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt#L571

Re-register all users for push notifications with new keys when upgrading to Mobile SDK 13

---

build.gradle.kts
publish/publish-root.gradle
publish/publish.sh

These changes allow us to publish to the new Maven Central Portal via the [OSSRH Staging API](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/), which is documented as:
> The Portal OSSRH Staging API is a partial reimplementation of the OSSRH / Nexus Repository Manager 2 Staging APIs. The intent of this service is to enable publishers who are using existing plugins to have a smooth migration to the Central Publisher Portal. We hope that over time plugins will adopt the [Portal API](https://central.sonatype.org/publish/publish-portal-api/) rather than rely on this service.
It does not sound like this intermediate API is going away anytime soon, but we should eventually upgrade to the new API when the Gradle Plugin we use supports it or an official Gradle Plugin is …

Update Maven Central publishing from OSSRH to Central Portal.

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityDelegate.java
libs/SalesforceSDK/src/com/salesforce/androidsdk/util/LogoutCompleteReceiver.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountManagerTest.java

We have limited knowledge of which account is undergoing logout in SalesforceSDK. The current implementation requires us to make assumptions about which account is undergoing logout which risks introducing race conditions or logic errors. 
* Pass UserAccount undergoing logout with the Logout Broadcast

@W-19307934 Add UserAccount to Logout Broadcast

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt

This extremely simple change fixes the issue because the default `WebChromeClient` handles the Javascript interaction/callback and provides the Android OS Date or Time picker out of the box... if it is supplied an _Activity_ `Context` by the WebView.

Fix date and time pickers in login webview.

---

libs/SalesforceSDK/res/values/sf__strings.xml
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/LoginViewModelTest.kt
libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/ui/LoginViewActivityTest.kt

- Add sf__clear_caches string resource
- Implement clearCaches method using webView.clearCache(true)
- Add Clear Caches menu item to login dropdown
- Add unit and UI tests for new functionality

Add Clear Caches menu item to login view

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/AppLockManager.kt
libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt

- Check if app is still locked before resetting lastBackgroundTimestamp.  This allowed users of React Native apps to the lock with a specific set of steps.  This issue did not affect Native or Cordova Hybrid apps.
- Fix Biometric Authentication button on Login screen not triggering action on press.

Biometric Authentication bugfixes

---

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt

The FLAG_SECURE constant was incorrectly imported from Display instead of WindowManager.LayoutParams. This fixes the import to use the correct location for the flag that prevents screenshots and screen recording of the login screen.

Fix FLAG_SECURE import in LoginActivity

---

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewCookieManager.kt
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SDKInfoPluginTest.java
libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewCookieManagerTest.kt

Added tests for the new method (inspectScope)
Also refactored setCookies to make it more testable and added tests

Hybrid app inspect scopes on user agent and warn if important ones are missing
