libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SalesforceSDKManagerWithSmartStore.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
A few beautiful bug fixes for our passcode users
=> Bug fix for clean up in the 'Forgot Passcode' use case

node/forcedroid.js, package.json
It was incorrectly pointing to ```unstable```.
=> Fixing branch for Cordova plugin

hybrid/test/ForcePluginsTest/src/com/salesforce/androidsdk/phonegap/SmartSyncJSTest.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncOptions.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java, native/SampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/loaders/ContactListLoader.java, native/SampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/ui/MainActivity.java
What's Left:
* Tests.
* Other odds and ends.
* Maybe an optimization to the fetch of ```LAST_MODIFIED_DATE``` - TBD.
=> First stab at merge mode LEAVE_IF_CHANGED implementation for sync up

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/Constants.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/MruSyncTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SoqlSyncTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SoslSyncTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java, native/SampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/loaders/ContactListLoader.java
SyncManager/SyncTarget refactored to have the actual fetching of records done by SyncTarget
=> Adding support for custom sync target

native/SampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/loaders/ContactListLoader.java, native/SampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/ui/MainActivity.java
Turns out that loader callbacks won't be triggered unless the load is triggered by ```LoaderManager```. For any other type of load, such as background sync, the ```Activity``` needs to be notified by a traditional eventing mechanism. This is primarily for the case where the ```Activity``` is foregrounded, but sync happens in the background.
=> Fixing quirky loader

hybrid/SampleApps/NoteSync/src/com/salesforce/samples/notesync/ContentSoqlSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/phonegap/SmartSyncPlugin.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/MruSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SoqlSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SoslSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncUpTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java, native/SampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/loaders/ContactListLoader.java
NB: diverging a bit from iOS implementation / will align iOS implementation in future pull request
TODO: hybrid side changes
=> Sync up target for android

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SalesforceSDKManagerWithSmartStore.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/DBOpenHelperTest.java
TODO Items:
* Change the filter for deletion to exclude global DBs.
* Add new tests.
* Verify existing tests pass.
=> First stab at adding global SmartStore

libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/TestSyncUpTarget.java
Tests refactoring + tests for "hard" failures (i.e. throwing exceptions) during sync up with locally created/updated/deleted items
=> More sync up tests

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
=> Tolerate the lack of existing Accounts on the device when app logs in for the first time

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/phonegap/SmartStorePlugin.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/SmartStoreInspectorActivity.java
Now making use of isGlobalStore passed to showInspector plugin
=> SmartStoreInspector can show user smartstore or default global smartstore

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
@khawkins @ktanna This should do it.
=> Allow retry of failed resync

libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartstoreFullTextSearchTest.java
The important one: testSearchWithFieldColonQueries
=> Addition FTS tests

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
Looks like we were hardcoding the ID field on ```Android```, but using the custom one on ```iOS```.
=> Use custom ID field if it is set

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
Adding device id to user agent
=> Advanced user tracking

native/README.md
=> One liner about ConfiguredApp and AppcConfigurator

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
This PR fixes issue [917](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/917).
There may be a better way of doing this null JSONObject checking, but this at least seems to work.
The manual tests used can be found in the issue ticket.
=> Bugfix/null integer + floating values cause crash

LICENSE.md
I put in the most recent licenses for sqlcipher and cordova. What else should we put in there?
@akhileshgupta Do we have an updated license for salesforce itself (first part of the file)?
=> Updated license file

node/forcedroid.js
Outstanding Items:
* Script to bring in the ```Gradle``` wrapper.
* Make it all work while importing into ```Android Studio```.
=> Making forcedroid work for native app generation

libs/SalesforceReact/build.gradle, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/ReactBridgeHelper.java, reactnative/ReactNativeTemplateApp/src/com/salesforce/samples/reactnativetemplateapp/MainActivity.java
Minor build issues - changes to template app will be in next PR
=> Pointing to react 0.16

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/AbstractSmartStoreTest.java
Android equivalent of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1357
=> Path through array

libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreJSTest.java
Tests passed without requiring any smartstore changes
=> Latest shared - running new js tests

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java
Query params were lost for delete/get/head
=> Fix for bug revealed in template app (query returning 400)

build.gradle, libs/SalesforceSDK/build.gradle
Switching to ```jCenter``` instead of ```MavenCentral```, since it's ```Google``` recommended.
=> Using official Gradle distribution of Volley from Bintray

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/SalesforceTLSSocketFactory.java
Bringing back our ssl socket factory
=> Networking was broken on 4.4

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java
Multipart post was not working because default type is "MIXED" when it should have been "FORM"
See https://square.github.io/okhttp/3.x/okhttp/okhttp3/MultipartBody.html
=> Multipart bug fix (revealed while working on sample app)

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceOAuthPlugin.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java, libs/SalesforceReact/res/values/strings.xml, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceOauthReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java, reactnative/ReactNativeTemplateApp/js/index.android.js
Application no longer does a login by default, instead the javascript needs to call authenticate if it needs to be authenticated.
First I had a shouldAuthenticate method in SalesforceReactActivity, but it was creating problems when the login automatically started in the middle of the react page running. 
This implementation allows for react native driven splash screen (see comment below).
=> Oauth bridge has authenticate method

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java
Using FLAG_SECURE for sensitive screens
=> Preventing screenshots in login activity and passcode activity

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartSyncPlugin.java
```JS``` and ```iOS``` coming up.
=> Adding hybrid implementation of 'cleanReSyncGhosts' API

build.gradle, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartSyncJSTest.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java
=> Adding hybrid test

.travis.yml, native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/ExplorerActivityTest.java
Also fix the file request test failures.
=> enable the build/test for all supported API versions

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/QuerySpec.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartSqlHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreJSTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/QuerySpecTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartSqlTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
With native/hybrid/react native support
Also added other smartstore tests recently added on iOS
=> Remove from soup by query

.travis.yml, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/files/FileRequests.java, native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/ExplorerActivityTest.java, native/test/TemplateAppTest/src/com/salesforce/samples/templateapp/PasscodeActivityTest.java
1. handle the 2nd lock screen on device before running test
2. keep the order as the put order for makeFileShare instead of the random order. The order for version 19 is different to the order for version 21 and 22 when using hashmap instead of linkedhashmap.
=> fix couple things

.gitignore, .npmignore
This will help us in gathering information when a new issue is created.
=> Add issue_template

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java, libs/test/SalesforceSDKTest/res/values/bootconfig.xml, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java, libs/test/SmartStoreTest/res/values/bootconfig.xml, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFullTextSearchTest.java, libs/test/SmartSyncTest/res/values/bootconfig.xml, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/ManagerTestCase.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/MetadataManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
Also update the sync up tests accordingly to remove the assumption that certain records need to be on test org already.
=> Update test to use the dedicate test account for Android test 

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/PasscodeManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java
* Keeping failed passcode attempts in pref file
* Not showing "forgot passcode" in passcode create/confirm screens
=>  Passcode can no longer be guessed as many times as desired

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java, native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/ui/MainActivity.java
Goes with the corresponding ```shared``` repo commit.
=> ReactNative Support for External Storage

libs/test/SalesforceSDKTest/res/values/bootconfig.xml, libs/test/SmartStoreTest/res/values/bootconfig.xml, libs/test/SmartSyncTest/res/values/bootconfig.xml
accidentally revoked the refresh token for test user..
=> update refresh token

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
Could be null, especially in tests.
=> Add null check for soupBlobString

UPGRADE.md
=> Upgrade doc for Android

README.md
=> What's New for Android

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java
For issue 
https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1237
=> fix issue where not setting network to false as should be

.npmignore, .travis.yml, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/DBOpenHelperTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartSqlExternalStorageTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreExternalStorageTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreLoadExternalStorageTest.java, node/forcedroid.js
The test_force part still fail for the pull request build since the tool pick the code from unstable branch only instead the unstable+the change. Locally, the failure is gone with this fix. And the build triggered by push on unstable should reflect the fix correctly.
=> fix the build and test failure on travis ci

libs/SalesforceHybrid/res/xml/config.xml, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceNetworkPlugin.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java, libs/test/SalesforceHybridTest/res/xml/config.xml, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SDKInfoPluginTest.java
Added a native `Cordova` plugin for networking.
=> Adding native network plugin implementation

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/PluginConstants.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartSyncPlugin.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreJSTest.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartSyncJSTest.java
Changes for ability to specify storeName, addition of Store related API(s).
=> Specify the target store name to achieve a soup per store

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/PluginConstants.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartSyncPlugin.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartSyncReactBridge.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
Similar changes made to react bridge as done in the cordova plugin. Added some checks for null prefixes used in dbnames.
=> Specify the target store name to achieve a soup per store (React native bridge) 

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
=> Fixing event name

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartSyncReactBridge.java
Also sharing some code between smartstore and smartsync react bridges
=> ReadableMap throws an error if key is not found

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartSyncPlugin.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartSyncReactBridge.java
Based on what we discussed @ivanbogdanov and @wmathurin.
=> Fixing bug with account state in plugins

libs/SalesforceSDK/build.gradle, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/files/FileRequests.java, libs/SmartStore/build.gradle
I've kept it available for unit tests to minimize the changes.
=> Remove Guava as a compile dependency.

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/EventBuilderHelper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/util/JSONObjectHelper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/util/test/JSONTestHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/JSONObjectHelperTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/DBOpenHelperTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/IndexSpecTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/QuerySpecTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreExternalStorageTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTestCase.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SoupSpecTest.java
Fix for bug reported https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/239
Also added a method to completely disable EventBuilderHelper so that test can be run individually (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/46e1fee96a9485c6a511a078c7fadbffc0fa64c9)
=> Null handling fix

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticatorService.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/util/MapUtil.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountManagerTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/ClientManagerTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/ManagerTestCase.java
=> Adding the ability to plug in custom identity keys and values

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java
Small change. Missed during refactoring of code from plugin to the SDK Manager.
=> Minor code change

README.md
@rwhitley and I reviewed it offline.
=> What’s New for 5.0

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AILTNPublisher.java
See iOS: https://git.soma.salesforce.com/SalesforceMobileSDK/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Analytics/SFSDKAILTNPublisher.m#L58
=> Exposing publishLogLines method to match iOS SDK

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticatorService.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/OAuth2Test.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/ClientManagerTest.java
Added ability to pass Additional Parameters using LoginOptions. Changed OAuth2  and ClientManager to ingest these parameters into auth/token endpoint & account manager.
=> Passing Additional Parameters to Auth endpoints

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
This adds the ability to plug a `TwinPrime` client in.
=> Exposing OkHttpClient.Builder for the app to plug in their own interceptors

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/AccountSwitcherActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
This extra specifies how the user was switched; either by logging in, logging
in for the first time, logging out or just switching between two authenticated
users.
=> Added an extra that's broadcast with USER_SWITCH_INTENT_ACTION

README.md
Added links to the HTML version of Dev Guide and the Mobile SDK Trail.
=> Added links to the Documentation section

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/AccountSwitcherActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java
This Bundle of extras could be used to pass additional
information during user switch. It will be part of the
broadcast intent sent after the user switch is completed.
=> Added an optional Bundle of extras to switchToUser

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncUpTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java
=> Latest shared

libs/SalesforceAnalytics/build.gradle, libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/FileLogger.java, libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/logger/SalesforceLogger.java, libs/SalesforceSDK/build.gradle, libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/logger/FileLoggerTest.java, libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/logger/SalesforceLoggerTest.java
This pull request adds a new logging framework in `MobileSDK`.
Features in this PR:
- Allows logging to console and to file.
- Log levels for console and file.
- Logging at the component level.
- Allows different log levels for each component.
- Allows a customizable circular buffer size of log file.
- One log file per component.
- File logger uses `Square's [Tape](http://square.github.io/tape/)` framework for fast I/O.
Coming soon:
- Dynamic tuning of log levels per component through custom attributes from connected apps.
- Retrieval of the log files for upload.
- Persistence of logging preferences in `SharedPrefs`.
=> Introducing SalesforceLogger - a new logging framework for MobileSDK components

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncUpTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTest.java
NB: runs correctly if children and parent are using standard ID field => for that reason it went unnoticed
=> Fixing incorrect code 

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SmartSyncLogger.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/ManagerTestCase.java
Added public static method to set log level
=> ManagerTestCase was not compiling anymore

install.sh, install.vbs, libs/SalesforceReact/build.gradle
It compiles.
Also template app compiles and runs. (However there is some work there because we use Navigator in the example app and that has been deprecated).
=> Moving to react native 0.45.1

install.sh, install.vbs, libs/SalesforceReact/build.gradle
This reverts commit 08b7cc656747e9797f4096a3bfc1a1e2dc048d58.
=> Revert "Moving to react native 0.45.1"

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/EventBuilderHelper.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java
Reporting run time in ailtn event
=> Capturing start and end time in sync state

.gitignore, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/PasscodeManager.java, libs/test/SalesforceSDKTest/res/values/bootconfig.xml, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKManagerTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/files/FileRequestsTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/PasscodeManagerTest.java, libs/test/SmartStoreTest/res/values/bootconfig.xml, libs/test/SmartSyncTest/res/values/bootconfig.xml, package.json
While testing dev53, I discovered tests failures that also exist in dev.
This PR is to fix them (then I'll merge dev into dev53).
=> Fixing tests

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
Fixing formatting and adding missing parameter descriptions.
=> Updating JavaDoc comments (RestRequest.java)

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartSyncPlugin.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/ReactBridgeHelper.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartSyncReactBridge.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/SmartStoreInspectorActivity.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartSyncJSTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java, native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/loaders/ContactListLoader.java
Hybrid + react native support
Also new syncDown/syncUp methods in SyncManager which take a syncName
=> Names for sync (part 2)

.circleci/Dockerfile, .circleci/ci-helper.sh, .circleci/config.yml
I expect the CircleCI build to fail because there are a few failing unit tests right now (but that proves the system works 😄 ).
=> Add CircleCI

README.md, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPCodeGeneratorActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPRequestHandler.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/SPRequestHandler.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
The SP app is now able to take the code generated by the IDP app and exchange it for a full set of credentials.
Next PR will have the actual flow wiring all the components together.
=> Adding SP handler code

.circleci/Dockerfile, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle, hybrid/HybridSampleApps/NoteSync/build.gradle, hybrid/HybridSampleApps/SmartSyncExplorerHybrid/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, libs/SmartSync/build.gradle, native/NativeSampleApps/AppConfigurator/build.gradle, native/NativeSampleApps/ConfiguredApp/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle, native/NativeSampleApps/SmartSyncExplorer/build.gradle
Brings support for `Android Studio 3.0` that just went GA and native support for `Kotlin`.
=> Adding support for Android Studio 3.0

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPAccountPickerActivity.java
This should close the loop on the IDP feature.
=> Adding support for 'user_hint' for IDP initiated flow

hybrid/HybridSampleApps/SmartSyncExplorerHybrid/assets/www/userstore.json, hybrid/HybridSampleApps/SmartSyncExplorerHybrid/assets/www/usersyncs.json, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/app/SalesforceHybridSDKManager.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/util/ResourceReaderHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/config/StoreConfig.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/SmartStoreInspectorActivity.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/config/SyncsConfig.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java, native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/loaders/ContactListLoader.java
* Configs are expected in assets/www directory
* SalesforceDroidGapActivity reads store and syncs configs
Todo: update sample apps in  Shared repo to use static configs - (maybe also handle static configs with mock store and sync manager)
=> Store and sync configs support in hybrid apps

.circleci/Dangerfile, .circleci/config.yml, .circleci/gitChangedLibs.rb
- Run Tests Conditionally, based on modified files
- Fix Danger for all users
=> PR CI Improvments

libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
=> Adding search test back

libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/config/SyncsConfigTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTestCase.java
Moving some cleanup to test super class
Calling sync state related methods on the sync manager instead of the underlying SyncState methods
=> Misc fixes

install.sh, install.vbs, libs/SalesforceReact/build.gradle, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/app/SalesforceReactSDKManager.java, package.json
- I also fixed the package.json formatting so it won't get messed up by npm in the future.
=> Upgrade to React Native v0.50.4

external/cordova/cordova.js, libs/SalesforceHybrid/build.gradle
Hybrid sample apps are working and hybrid tests are passing.
=> Upgrading to Cordova 6.4.0

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java
Copied the similar null checks from other reset methods;
MetadataManager.reset(userAccount);
CacheManager.softReset(userAccount);
=> UserAccount null check in SyncManager.reset(UserAccount)

.circleci/Dockerfile, gradle.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle, hybrid/HybridSampleApps/NoteSync/build.gradle, hybrid/HybridSampleApps/SmartSyncExplorerHybrid/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, libs/SmartSync/build.gradle, native/NativeSampleApps/AppConfigurator/build.gradle, native/NativeSampleApps/ConfiguredApp/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle, native/NativeSampleApps/SmartSyncExplorer/build.gradle
Based on `Android Studio`'s recommendation.
=> Bumping up Gradle tools version to the latest

libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/DBOpenHelperTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartSqlExternalStorageTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartSqlTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreAlterTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFTSExternalStorageTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFullTextSearchSpeedTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreFullTextSearchTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreLoadTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreLoadTestCase.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreOtherLoadExternalStorageTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreOtherLoadTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTestCase.java
Had to split some of the test classes - since one cannot mix parametrized tests with non-parametrized tests
=> Using junit4's parametrized tests in smartstore load tests

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceKeyGeneratorTest.java
Option to get an encoded public key string.
=> Provided an option to generate a RSA-2048 keypair 

libs/SalesforceSDK/res/values/strings.xml, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ApiVersionStrings.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/MetadataManager.java, libs/test/SalesforceAnalyticsTest/res/values/bootconfig.xml, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java, libs/test/SalesforceSDKTest/res/values/bootconfig.xml, libs/test/SmartStoreTest/res/values/bootconfig.xml, libs/test/SmartSyncTest/res/values/bootconfig.xml
We need this for the `BundleID` change.
=> Upgrading to v42.0

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceKeyGeneratorTest.java
Adding asymmetric crypto methods and tests.
=> Adding encryption and decryption methods for RSA

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
Also added test (which fails with old code)
=>  Improved logic to recognize soup column in result set

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java
Allows an app to customize the fingerprint dialog's layout.
=> Making fingerprint layout customizable

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/SPRequestHandler.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigTask.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/util/AuthConfigUtil.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java
Reads from `.well-known/auth-configuration`.
=> Adding support for runtime config of browser login through SSO auth config

README.md, libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/SalesforceKeyGeneratorTest.java, native/README.md
Added new methods that take an additional parameter, `iv`. Existing behavior and APIs remain the same.
=> Adding the ability to pass in IV

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
Util method to get back `byte[]`.
=> Adding util method to get back bytes

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
A simple API to use the existing `Cipher` to decrypt bytes directly.
=> Adding API to decrypt bytes directly

.circleci/ci-helper.sh, .circleci/config.yml
- Change nightly to API22, API24 emulator isn't working anymore.
- Skip running tests on merge builds
=> Fix Nightly and Merge Builds

.circleci/config.yml
=> Missing hybrid test results

.circleci/codecov.yml, .circleci/config.yml
=> Adding SalesforceReact tests to nightly test runs

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java
@khawkins I assume you want this on `Android` too?
=> Device attributes should be decoupled from user context

README.md, UPGRADE.md
Reviewed with @rwhitley offline.
=> What's New and Upgrade Steps for Mobile SDK 6.1

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.java
In some instances, if the API takes a long while to return, the service will hold a `WAKE_LOCK` for too long. It's a good idea to specify a timeout while acquiring a wake lock. Also cleaned up some lint warnings on NPEs.
=> Adding timeout for wake lock

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartStorePlugin.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreLoadJSTest.java
Fix for:
test[testRegisterWithSpec] - com.salesforce.androidsdk.phonegap.SmartStoreJSTest
test[testUpsertConcurrentEntries] - com.salesforce.androidsdk.phonegap.SmartStoreLoadJSTest
=> Fix hybrid unit tests

native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/PasscodeActivityTest.java, native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/ServerPickerActivityTest.java
Fix tests:
testAddInvalidUrl - com.salesforce.samples.restexplorer.ServerPickerActivityTest
testForgotPasscodeLink - com.salesforce.samples.restexplorer.PasscodeActivityTest
=> Fix RestExplorer Tests

libs/SalesforceSDK/res/layout/sf__login.xml, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
Current layout design causes blank space to appear in the view if the content doesn't fill the entire height.  
Change allows the webview to fill the entire height of the viewport and control it's own scroll instead of placing it inside of a scrollview.
=> Updating sf__login.xml to no longer place webview in a scrollview and fit height

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java
This PR removes additional whitespace from hostname and label.
=> Handling whitespace at the end

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceOauthReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java
Also removing unused argument in API.
=> Use SalesforceReactSDKManager instead of SalesforceSDKManager for React library

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/MruSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTargetHelper.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncUpTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/RefreshSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SoslSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncUpTarget.java
Auto-generated fixes by `Android Studio` for a bunch of warnings.
=> Removing a bunch of warnings

build.gradle, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/CacheManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/MetadataManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/model/SalesforceObject.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/model/SalesforceObjectLayoutColumn.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/model/SalesforceObjectType.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/model/SalesforceObjectTypeLayout.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/LayoutSyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SyncDownTarget.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/Constants.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestRequestTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/CacheManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/MetadataManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
This uses the new `UI SDK` API endpoint.
=> Adding sync down target for object layout

libs/SalesforceSDK/res/values/sf__strings.xml
String from the toast is not applicable anymore. Updated.
=> Removed extra string from the toast

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncUpTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/ParentChildrenSyncTestCase.java
Android equivalent of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2522
=> Fix for parent-child sync up bug

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/LayoutSyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/model/Layout.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/model/SalesforceObject.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/LayoutSyncDownTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/LayoutSyncManagerTest.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
- Introduces a data model encapsulation for layout data.
- Introduces a new manager class that makes it easy to sync layout data and returns a strongly-typed object for ease of use. This manager takes care of indexing the data, storing and retrieving from `SmartStore`.
- Introduces 3 simple cache policies that can be specified while retrieving data.
- Tests for the new manager class.
=> Creating high level utility to sync layout data with cache policies (LayoutSyncManager)

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/MetadataSyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/model/Metadata.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/Constants.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/MetadataSyncManagerTest.java
Equivalent of [this PR](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1695) for metadata.
=> Creating high level utility to sync metadata with cache policies (MetadataSyncManager)

libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartSqlTest.java
No code change.
Just a test demonstrating how to proceed:
index the field as a JSON1 field
in SmartSql look for 0 (false) or 1 (true) because SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).
=> Consistent indexing of booleans (between iOS and Android) in SmartStore

libs/SalesforceSDK/res/values/sf__colors.xml, libs/SalesforceSDK/res/values/sf__dimens.xml, libs/SalesforceSDK/res/values/sf__strings.xml
Picked up by `lint` in the previous PR.
=> Removing unused resources

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SDKInfoPlugin.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
We already do this on `iOS`. Adding this to `Android` to bring it to parity.
=> Adding build number to app version

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartSyncReactBridge.java
In React Native cleanResyncGhosts success callback doesnt return numrecords
=> cleanResyncGhosts success return numRecords

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/ManagerTestCase.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/manager/SyncManagerTest.java
Some of these tests weren't cleaning up after.
=> Cleaning up upon test completion

libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, libs/SmartSync/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle, native/NativeSampleApps/SmartSyncExplorer/build.gradle
- Upgrades test and support library versions to the latest.
- Removes some obsolete Gradle steps we had.
=> Some Gradle dependency cleanup

.circleci/ci-helper.sh, .circleci/config.yml
- Archive logcat output for every test run so failures can quickly be diagnosed.
- Add sdcard to CircleCi emulator to fix a bunch of tests across SmartSync, Hybrid and React.
- Remove unnecessary lines in yaml.
=> Capture Logcat and Fix Env Test Failures

libs/SalesforceSDK/build.gradle, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
=> Upgrading libraries to the latest

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/ReactBridgeHelper.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartSyncReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java
Set message from error to current sync state
Return sync state to react native instead of "Sync failed" for sync failure
=> Add error message to SyncState for failed sync down

libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.java
After appName change in SFDCRegistrationService, need to make similar change for unregister to avoid swallowed exception
=> Get firebase instance based on appName in unregister

libs/SalesforceSDK/AndroidManifest.xml
This locks down the login screens and related ones on portrait mode.
=> Locking down login related activities on portrait mode

external/cordova/cordova.js, libs/SalesforceHybrid/build.gradle, libs/test/SalesforceAnalyticsTest/res/values/bootconfig.xml, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java, libs/test/SalesforceReactTest/src/com/salesforce/androidsdk/reactnative/util/ReactTestActivity.java, libs/test/SalesforceSDKTest/res/values/bootconfig.xml, libs/test/SmartStoreTest/res/values/bootconfig.xml, libs/test/SmartSyncTest/res/values/bootconfig.xml
Upgrading to `cordova@7.1.2` to solve the Google Maven repository problem.
Ran the apps `SmartSyncExplorerHybrid` and `AccountEditor` and exercised functionality in both apps. The apps are working fine.
=> Upgrading to Cordova 7.1.2

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
Corresponding change on iOS: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2745
=> Better special character handling in SmartStore

libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/JavaScriptPluginVersionTest.java, setversion.sh
Also changed testJavaScriptPluginVersionsWithNewVersion so it no longer needs to be changed with every release
=> Improved setversion.sh that takes care of build.gradle files and generate_doc.sh

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceNetworkPlugin.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ForceJSTest.java, libs/test/SalesforceReactTest/src/com/salesforce/androidsdk/reactnative/ReactNetTest.java
Native implementation of [this PR](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/112) on `Android`.
=> Adding support for unauthenticated ReactNative REST requests

external/cordova/cordova.js, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, libs/SmartSync/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle
The release is in voting stage right now and should go out in about 48 hours.
=> Upgrading to Cordova 8.0.0

libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SmartStoreReactBridge.java
Introduced [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1850).
=> Fixing compilation error in SalesforceReact

libs/test/SalesforceReactTest/src/com/salesforce/androidsdk/reactnative/ReactSmartStoreTest.java
See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/114
=> Running new smartstore react native test from android also

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/BatchingSyncUpTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/BatchingSyncUpTargetTest.java
=> Lining up BatchingSyncUpTarget constructors with iOS's

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/KeyStoreWrapperTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/SalesforceKeyGeneratorTest.java
This pull request consolidates all the existing `KeyStore` functionality in a single place.
Next steps:
- Add methods for generating `ECC` keys.
- Migrate stored key from `SharedPrefs` to `KeyStore`.
- Upgrade code.
=> Consolidating KeyStore functionality in a single class

.circleci/ci-helper.sh, .circleci/setTestCreds.rb, libs/test/SalesforceAnalyticsTest/res/values/bootconfig.xml, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/SmartStoreLoadJSTest.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java, libs/test/SalesforceReactTest/src/com/salesforce/androidsdk/reactnative/util/ReactTestActivity.java, libs/test/SalesforceSDKTest/res/values/bootconfig.xml, libs/test/SmartStoreTest/res/values/bootconfig.xml, libs/test/SmartSyncTest/res/values/bootconfig.xml
- CI should seamlessly pickup creds
- Quick setup is documented internally
- External developers should supply their own creds to run tests locally.
=> Pull test creds from env

libs/SmartSync/AndroidManifest.xml, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java, libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java, libs/test/SalesforceHybridTest/AndroidManifest.xml, libs/test/SalesforceReactTest/AndroidManifest.xml, libs/test/SalesforceSDKTest/AndroidManifest.xml, libs/test/SmartStoreTest/AndroidManifest.xml, libs/test/SmartSyncTest/AndroidManifest.xml, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/util/SyncStateTest.java
* Added index (on status) in syncs soup
* Changed indexes on syncs soup to json1
* Added clean up method (and calling it at SyncManager creation)
* Added tests
=> Sync manager cleans up interrupted syncs state at startup

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java, native/NativeSampleApps/RestExplorer/res/xml/servers.xml
Testing upgrade steps with sample app.
=> Removing memory caching and adding upgrade steps

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/SoqlSyncDownTarget.java, libs/test/SmartSyncTest/src/com/salesforce/androidsdk/smartsync/target/SoqlSyncDownTargetTest.java
Fix for https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1787
=> Handling subqueries when computing soql for remote ids

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceNetworkPlugin.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/ui/SalesforceReactActivity.java, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java, libs/test/SalesforceReactTest/src/com/salesforce/androidsdk/reactnative/util/ReactTestActivity.java
1) Hybrid / react pull test credentials in the clientManager built by the react / hybrid test activity but unauthenticated rest client were built with the clientManager obtained from SalesforceSDKManager
2) Hybrid / react net plugin didn't not expect end point to be null, but it could be null when hitting other servers (the path will then contain the full url).
=> Issues with unauthenticated requests in hybrid / react native app/tests

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
If browser is not installed, show a `Toast` message and exit gracefully.
=> Fixing crash when browser is not installed

libs/SalesforceSDK/AndroidManifest.xml, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/PasscodeManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/PasscodeManagerTest.java, native/NativeSampleApps/test/RestExplorerTest/src/com/salesforce/samples/restexplorer/PasscodeActivityTest.java
- Fix UI not changing after first unlock on app upgrade
- Fix keyboard focus
- Don't allow passcode length to be lowered
- Fix passcode does not match reentering when creating
=> Passcode UI updates

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java
@chrlie Here's the fix we discussed.
=> Fixing corner cases around deferred authentication

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
This fixes an issue with re-login after logging out for users with push notifications enabled.
=> Fixing issue with re-login after logging out

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
(getEncryptionKey is prohibitively slow without it
=> Bringing back encryption key caching

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
Bringing back encryption key caching
=> Cherry-picking pull request #1922 from wmathurin/dev

setversion.sh
Was not setting tag correctly in SalesforceReact's package.json
=> Fixing setversion.sh

libs/SmartSync/src/com/salesforce/androidsdk/smartsync/util/SyncState.java
To be consistent with ios:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2904
=> Adding getter for name

README.md, libs/SmartStore/build.gradle, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/SmartStoreTest.java
=> Moving to SQLCipher 4.2.0

libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LoginServerManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/config/RuntimeConfig.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/config/RuntimeConfigTest.java
MDM: Allowing hosts and their labels to be passed as ...
=> Cherry picking MDM fix to master

libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java
Bringing in the change from SalesforceApp fork
=> @W-6237507 Replace hardcoded id with the suffix

gradle.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle, hybrid/HybridSampleApps/NoteSync/build.gradle, hybrid/HybridSampleApps/SmartSyncExplorerHybrid/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, libs/SmartSync/build.gradle, native/NativeSampleApps/AppConfigurator/build.gradle, native/NativeSampleApps/ConfiguredApp/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle, native/NativeSampleApps/SmartSyncExplorer/build.gradle
This is a legacy artifact from the old build system.
=> Removing unnecessary hardcoded build tools version

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java
(PR'd  https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1992 to dev branch as requested https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1992#issuecomment-543090448)
The oauth refresh interceptor should close previous response before proceeding to the next, else the following exception is thrown; and the app fatals..
fixes #1955
see also
https://github.com/square/okhttp/issues/4986#issuecomment-508275423
````
09-12 10:40:03.633 16302 16432 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-12 10:40:03.633 16302 16432 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
09-12 10:40:03.633 16302 16432 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) …
```
=> oauth refresh interceptor should close previous response before proceeding to the next

gradle.properties, libs/SalesforceHybrid/build.gradle
Cordova android 8.1.0 does a ParseInt on cdvCompileSdkVersion.
=> Moving to cordova android 8.1.0

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/ParentChildrenSyncUpTarget.java, libs/test/MobileSyncTest/res/raw/usersyncs.json, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/config/SyncsConfigTest.java
* usersyncs.json config in tests has example of every sync target
* Each sync config is validated in depth by test code
* same test config and tests on iOS (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3086)
=> More complex tests around syncs configs

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/AccountSwitcherActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/DevInfoActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/FingerprintAuthDialogFragment.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceServerRadioButton.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKManagerTest.java, native/NativeSampleApps/ConfiguredApp/src/com/salesforce/samples/configuredapp/ui/MainActivity.java, native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/DetailActivity.java, native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/LogoutDialogFragment.java, native/NativeSampleApps/MobileSyncExplorer/src/com/salesforce/samples/mobilesyncexplorer/ui/MainActivity.java
- Remove disable and force APIs in favor of just setting theme.
- Remove need to send an activity to check if dark theme should be shown.
- Add tests.
=> Improve dark theme APIs.

.circleci/config.yml, libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/app/MobileSyncUpgradeManager.java, libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/config/SyncsConfig.java, libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/manager/LayoutSyncManager.java, libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/LayoutSyncDownTarget.java, libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/util/Constants.java, libs/SalesforceSDK/build.gradle, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushNotificationDecryptor.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java, libs/test/MobileSyncTest/res/raw/usersyncs.json, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/config/SyncsConfigTest.java, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/LayoutSyncManagerTest.java, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/SyncManagerTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestRequestTest.java
- Details [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3157).
- This should now support everything listed under `UI API` [here](https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_resources_record_layout.htm).
- Added new tests for all the new functionality/fields.
=> Enhancing LayoutSyncManager to support more fields and use cases

libs/SalesforceSDK/src/com/salesforce/androidsdk/util/ManagedFilesHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/app/SmartStoreSDKManagerTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/KeyValueEncryptedFileStoreTest.java
Not done yet: cleanup key value stores when user logs out
=> File based key value store

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
Follow-up to https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2057
=> db.delete() does not like null anymore

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/KeyValueEncryptedFileStoreTest.java
That will make key rotations easier.
=> Adding a changeEncryptionKey method to key value store

README.md
Shows the latest GitHub release (sorted by SemVer)
Example: ![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/forcedotcom/SalesforceMobileSDK-Android?sort=semver)
=> Github Release badge

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
We should handle all auth flow errors equally, otherwise it leaves the app in a weird state where the account isn't persisted but the login page isn't showing either.
=> Handling OAuth flow errors and failure cases

libs/SalesforceSDK/AndroidManifest.xml
Addressing https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/169
=> Login screen should scroll when keyboard shown

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTarget.java, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/SyncManagerTestCase.java, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTargetTest.java
Fixes the infinite loop reported here: forcedotcom/SalesforceMobileSDK-ReactNative#168
=> Better handling of bad or missing sobject type during sync up

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceNetworkPlugin.java, libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java
For discussion here: https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/pull/138#discussion_r453828871
=> Rest error dictionary

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
This will get triggered only in expired token flows.
=> Add missing upgrade key

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
Tested by adding a flavor to MobileSyncExplorer:
=> Fix debug menu for apps with product flavors.

libs/SalesforceSDK/res/values/sf__styles.xml, libs/SmartStore/AndroidManifest.xml, libs/SmartStore/build.gradle, libs/SmartStore/res/drawable/sf__inspector_key_icon.xml, libs/SmartStore/res/drawable/sf__inspector_store_icon.xml, libs/SmartStore/res/layout/sf__inspector_key_value_results_cell.xml, libs/SmartStore/res/layout/sf__inspector_menu_popup_item.xml, libs/SmartStore/res/layout/sf__key_value_inspector.xml, libs/SmartStore/res/values/sf__strings.xml, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/app/SmartStoreSDKManager.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/KeyValueStoreInspectorActivity.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/store/KeyValueStoreInspectorActivityTest.java
=> Add KeyValueEncryptedFileStore Inspector to DevMenu.

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
Some cleanup to ensure that `file.close()` will always be called and the stream is reliably closed.
=> Fixing file.close() and adding comments about encryption/decryption

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java
Leaked closeable found with https://wh0.github.io/2020/08/12/closeguard.html
=> FileInputStream was never closed in getStream

install.sh, libs/SalesforceReact/build.gradle, libs/SalesforceReact/package.json
NB: Needs https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/214
=> Moving to react native 0.63.4 

libs/SalesforceSDK/res/layout/sf__server_picker.xml, libs/SalesforceSDK/res/values/sf__strings.xml, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
- Fix add connection button showing on top of a full page list of servers.
- Fixed invalid servers being able to be added.
- Fixed Toast message for invalid url and added message for missing name.
- Improved url validity by checking for a dot.
- Adding a new connection now scrolls the list (if long enough) to show it is selected.
=> Fix Server Picker Bugs

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/ui/KeyValueStoreInspectorActivity.java
=> Add long press copy action to Key-Value Inspector.

build.gradle, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClient.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClientHelper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushNotificationDecryptor.java
This PR adds logic for universal session redirection for hybrid apps within our webview.
Test Cases:
- Access token expired -> detect, refresh and reload page.
- Refresh token expired -> detect, refresh and trigger log out flow.
- Unauthenticated to authenticated (Communities use case).
=> Adding Universal Session Redirect Detection for Hybrid Apps

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartSqlHelper.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartSqlExternalStorageTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartSqlTest.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreAlterTest.java
Thanks to json1, we can query by or return non-indexed field (as long as the data is stored in the database).
=> SmartSql now supports selecting or filtering by non-indexed field.

libs/MobileSync/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle
=> Fixing publish version

libs/SalesforceSDK/build.gradle, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/ScreenLockManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivityDelegate.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ScreenLockActivity.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/ScreenLockManagerTest.java
- Improve when ScreenLock is shown by using lifecycle apis and fix associated issues.  
- Cleanup LockScreenManager API.   
- Fix an upgrade issue related to future logouts.
=> Fix ScreenLock issues

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
These new fields are optional in the new hybrid OAuth flow.
=> Adding missing optional fields in UserAccount object

native/NativeSampleApps/RestExplorer/res/layout/explorer_header.xml, native/NativeSampleApps/RestExplorer/res/values/strings.xml, native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/ExplorerActivity.java, native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/RestExplorerApp.java
Would have been much simpler to just add a button to the app to copy to clipboard but this is a good example of how an app could extend our DevMenu.
=> Add copy credentials to clipboard button to RestExplorer.

build.gradle, gradle.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle, hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle, hybrid/HybridSampleApps/NoteSync/build.gradle, libs/MobileSync/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, native/NativeSampleApps/AppConfigurator/build.gradle, native/NativeSampleApps/ConfiguredApp/build.gradle, native/NativeSampleApps/MobileSyncExplorer/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle
- Bumping up `targetApiVersion` to `31`.
=> Adding Support for Android S

.circleci/config.yml, gradle.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle, hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle, hybrid/HybridSampleApps/NoteSync/build.gradle, libs/MobileSync/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClient.java, libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceWebViewClientHelper.java, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/AndroidManifest.xml, libs/SalesforceSDK/build.gradle, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/CustomServerUrlEditor.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java, libs/SmartStore/build.gradle, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/util/SOQLMutatorTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java, native/NativeSampleApps/AppConfigurator/build.gradle, native/NativeSampleApps/ConfiguredApp/build.gradle, native/NativeSampleApps/MobileSyncExplorer/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle
I tried to fix/update everything API 23/24 related that I could find.
=> Update minSDKVersion from API 23 to 24.

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/model/InstrumentationEvent.java, libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java, libs/test/SalesforceAnalyticsTest/src/com/salesforce/androidsdk/analytics/store/EventStoreManagerTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManagerTest.java
- Batch read and publish of instrumentation events to reduce memory
footprint
=> Batch read and publish of Instrumentation Events

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java
=> Add extra check that passcode was enabled before enabling ScreenLock on upgrade.

build.gradle, gradle.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle, hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle, hybrid/HybridSampleApps/NoteSync/build.gradle, libs/MobileSync/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, native/NativeSampleApps/AppConfigurator/build.gradle, native/NativeSampleApps/ConfiguredApp/build.gradle, native/NativeSampleApps/MobileSyncExplorer/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle
- Latest AGP version.
- Target API is now `API 32`.
=> Time to move to API 32

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/AlterSoupLongOperation.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SoupSpec.java, libs/test/SmartStoreTest/src/com/salesforce/androidsdk/smartstore/store/SmartStoreAlterTest.java
The plan is to remove them in 11.0.
=> Deprecating external storage and soup spec

build.gradle, gradle/wrapper/gradle-wrapper.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle, hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle, hybrid/HybridSampleApps/NoteSync/build.gradle, libs/MobileSync/build.gradle, libs/SalesforceAnalytics/build.gradle, libs/SalesforceHybrid/build.gradle, libs/SalesforceReact/build.gradle, libs/SalesforceSDK/build.gradle, libs/SmartStore/build.gradle, native/NativeSampleApps/AppConfigurator/build.gradle, native/NativeSampleApps/ConfiguredApp/build.gradle, native/NativeSampleApps/MobileSyncExplorer/build.gradle, native/NativeSampleApps/RestExplorer/build.gradle
Auto-generated by `Android Studio`.
=> Upgrading to AGP 7.1.0 and removing Gradle warnings

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/CompositeRequestHelper.java, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/target/CollectionSyncUpTargetTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
Also fixed upsert case for CollectionSyncUpTarget (brought back test)
=> Refining sobject collection tests (to line up with iOS)

build.gradle, gradle/wrapper/gradle-wrapper.properties
Support the latest `Android Studio`.
=> Upgrading to AGP 7.2.1

libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/CompositeRequestHelper.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java, libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/manager/ManagerTestCase.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
Also having allOrNone parameter in second place for all sObject collection methods
=> allOrNone parameter was missing for sObject collection delete

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
=> Caching appName

.circleci/config.yml, external/cordova/cordova.js, hybrid/HybridSampleApps/AccountEditor/AndroidManifest.xml, hybrid/HybridSampleApps/MobileSyncExplorerHybrid/AndroidManifest.xml, hybrid/HybridSampleApps/NoteSync/AndroidManifest.xml, libs/SalesforceHybrid/build.gradle, libs/SalesforceHybrid/res/values/themes.xml, libs/test/SalesforceHybridTest/AndroidManifest.xml, libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/ui/SalesforceHybridTestActivity.java
The cordova.js was copied from a project generated with cordova cli and cordova-android 11.0.0
=> Moving to cordova android 11.0.0

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/RestClientTest.java
It has been available for iOS for a long time
=> Add RestRequest factory method for QueryAll

libs/SalesforceSDK/build.gradle
Interestingly the package is still com.squareup.okhttp3 ;-)
=> Upgrading to okhttp 4

libs/SalesforceReact/build.gradle, libs/SalesforceReact/package.json, libs/test/SalesforceReactTest/src/com/salesforce/androidsdk/reactnative/util/ReactNativeTestHost.java
Successfully ran `SalesforceReact` tests (but one flaps a lot).
=> Move to React Native 0.70.1

libs/SalesforceSDK/res/values/bootconfig.xml, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/config/BootConfig.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/BiometricAuthenticationManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/ScreenLockManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/interfaces/BiometricAuthenticationManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/interfaces/ScreenLockManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/BiometricAuthenticationManagerTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/ScreenLockManagerTest.kt
- Change isEnabled and isLocked functions to properties.
- Move Biometric Authentication Timeout to connected app custom attribute from BootConfig value.
- Update connected app attributes to `ENABLE_BIOMETRIC_AUTHENTICATION` and `REQUIRE_BIOMETRICS_AFTER`.
=> Cleanup Biometric Authentication

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java
🎸 _Ready For Review!_ 🥁
This pull request adds awareness of the new `is_salesforce_integration_user` user account attribute and uses it to prohibit login.  Thanks, @wmathurin, for the discussion on this one!
=> @W-13186970: [Android] Enable blocking of mobile app access to "salesforce integration" users in Mobile SDK

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LegacyAdminSettingsManager.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManagerTest.kt
The connected app custom attributes screen allows custom attributes to be calculated fields (and they can be user specific See https://help.salesforce.com/s/articleView?id=sf.connected_app_edit_custom_attributes.htm&type=5
=> Custom attributes are now saved in per-user shared prefs

libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/util/AuthConfigUtilTest.java
Update test expectations to match the auth config of the test: https://foundation.my.site.com/.well-known/auth-configuration
=> Fix testGetSSOUrls.

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
This is a followup to my PR to Support Predictable System Back (#2463)
=> Fix back gesture behavior when switching servers

libs/SalesforceReact/build.gradle.kts, libs/SalesforceReact/package.json
To match https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/340
=> Update React Native to 0.70.13.

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, native/NativeSampleApps/RestExplorer/src/com/salesforce/samples/restexplorer/RestExplorerApp.java
Through SalesforceSDKManager, app can specify an alternate browser or indicate it wants the default to be used.
=> Configurable custom tab browser

libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPAuthCodeHelper.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestRequest.java
It's faster than limits and is also available to all API users.
=> Using resources by version call to rehydrate session

.circleci/Dangerfile_Lib.rb, .circleci/config.yml
This should be more efficient and hopefully git rid of our OOM testing issues.
=> Run static analysis per library instead of for the project.

libs/test/MobileSyncTest/src/com/salesforce/androidsdk/mobilesync/util/SOQLMutatorTest.java
Trying to repro https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/331
=> Adding test to try and repro customer issue

hybrid/HybridSampleApps/AccountEditor/build.gradle.kts, hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts, libs/MobileSync/build.gradle.kts, libs/SalesforceAnalytics/build.gradle.kts, libs/SalesforceHybrid/build.gradle.kts, libs/SalesforceReact/build.gradle.kts, libs/SmartStore/build.gradle.kts, native/NativeSampleApps/AppConfigurator/build.gradle.kts, native/NativeSampleApps/ConfiguredApp/build.gradle.kts, native/NativeSampleApps/RestExplorer/build.gradle.kts
SalesforceSDKManager's getBuildConfigValue looks for it
=> Generating BuildConfig

libs/SalesforceReact/build.gradle.kts, libs/SalesforceReact/package.json
I ran react-native cli to create a new app from a template then compared the output (package.json, podfile etc).
=> Moving to React Native 0.73.6

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/interfaces/NativeLoginManager.kt
This is ready for final review now that it has been tested fully in the updated template app.  See https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/400
Thanks! 🤘🏻
=> @W-14584405: [Android] OTP implementation

libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/AppLockManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/BiometricAuthenticationManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/ScreenLockManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/interfaces/BiometricAuthenticationManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/security/interfaces/ScreenLockManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ScreenLockActivity.java
- Send AppUnlocked event where appropriate.
- Add locked variable to ScreenLockManager.
=> ScreenLock Updates

libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java
OAEP uses a separate hash invocation for MGF (mask generation function) and for the hashing of the label.
Most libraries use the same hash algorithm for MGF and the hashing of the label. 
But Java uses a different hash algorithm: it defaults to SHA-1 when using  the cipher RSA/ECB/OAEPWithSHA-256AndMGF1Padding. 
iOS uses SHA-256 when using the cipher kSecKeyAlgorithmRSAEncryptionOAEPSHA256.
Java provides a way to override the default and specify SHA-256 as the hash for MGF (and conversely iOS does not provide a way to specify a different hash function) ==> we need to make sure to explicitly set SHA-256 has the hash function for MGF on both the server and Android.
=> Use SHA-256 for MFG during push notification decryption

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/IDPAuthCodeHelper.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt
I think this just got lost in the `SalesforceSDKManager` Java to Kotlin conversion.
=> Make useHybridAuthentication a settable variable.

libs/SalesforceSDK/src/com/salesforce/androidsdk/developer/support/notifications/local/ShowDeveloperSupportNotifier.kt
I also removed (now) unnecessary API level checks.
=> Don't prompt for dev menu notification permission if disabled.

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/interfaces/NativeLoginManager.kt
🎸 _Review For Review!_ 🥁
Now we have headless registration via the Salesforce Identity API as well.  This will look very familiar to reviewers of other recent headless identity flow pull requests.
=> @W-14662364: [Android] Add additional Native Login Feature: User Registration

libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/AnalyticsPublishingWorker.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt
This applies some code review feedback as a fast-follow to #2587.  The crux change is switching both tasks to a few enum types.
=> @W-16176547: [MSDK Android] Code Review Follow-Up For W-15993541/W-15993636 - AILTN Publish & Push Notification Registration Updates

libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java
🥁 _*Ready For Review*_ 🤘🏻
This corrects a potential crash where a call the load the SQLCipher library was outside of the critical section to synchronize multithreaded access to it.  The trick was that only the call to `AtomicBoolean.compareAndSet(...)` was thread safe.  Once it completed and `loadLibrary` was working other threads could continue.
There was a way to do this with `AtomicBoolean` which I tried in the first commit.  Then, I though more about the `Lock` object I often use with Kotlin Concurrent's `withLock` extension.  There _is_ a way to do that in Java so we move one step towards Kotlin conversion here.  Also, we don't seem to need the boolean as `loadLibrary` gracefully completes in milliseconds once the library is already loaded.
I'd previously observed that changes to the …
=> @W-17092709: [MSDK Android] Cannot Log In To AccountEditor Hybrid Sample App

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/JwtAccessToken.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/JwtAccessTokenTest.java
Showing JWT expiration date/time in dev infos dev menu.
=> Convenience method to get JWT expiration date/time.

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java
Possibility of NPE was introduced during this refactor: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2616
=> No NPE if refresh token is revoked by admin

libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/SfapApiChatGenerationsResponseBody.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/SfapApiClient.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/SfapApiFeedbackRequestBody.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/SfapApiGenerationsResponseBody.kt
While I was working on the iOS counterpart, I noticed a handful of items for Android that would be great to have.  So, here's a quick pull request to bring the two in sync.
=> @W-17615983: [Android] REST wrappers for select SFAP APIs - iOS Consistency Updates

.github/workflows/reusable-workflow.yaml, build.gradle.kts, buildSrc/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, hybrid/HybridSampleApps/AccountEditor/build.gradle.kts, hybrid/HybridSampleApps/MobileSyncExplorerHybrid/build.gradle.kts, libs/MobileSync/build.gradle.kts, libs/SalesforceAnalytics/build.gradle.kts, libs/SalesforceHybrid/build.gradle.kts, libs/SalesforceReact/build.gradle.kts, libs/SalesforceSDK/build.gradle.kts, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt, libs/SmartStore/build.gradle.kts, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/LoginViewModelTest.kt, native/NativeSampleApps/AppConfigurator/build.gradle.kts, native/NativeSampleApps/ConfiguredApp/build.gradle.kts, native/NativeSampleApps/RestExplorer/build.gradle.kts
🎸 _*Ready For Full Review!!!*_ 🥁
This updates the Android templates where needed with MSDK support for Jetpack Compose.
=> @W-17433472: Update Templates

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt
=> W-17867075: [MSDK Android] Login View Custom Bottom App Bar Button In-Operative

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/LoginView.kt
=> W-17867189: [MSDK Android] Login View Bottom App Bar Shown Even When Empty

libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/PickerBottomSheet.kt
=> Fix unfocused text field color.

libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/SalesforceActionableNotificationContent.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsActionsResponseBody.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsApiClient.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsApiErrorResponseBody.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsApiException.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsTypesResponseBody.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/SfapApiClient.kt
🤘🏻 *_Ready For Review_* 🎸
This builds on our earlier actionable notifications effort by adding the ability for app's to marshal the new notification content for use in displaying notifications plus the ability to submit notification actions to the API.
=> @W-18079771: Actionable Notifications (Android) Invoke Actionable Notification

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticationUtilities.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/SPAuthCodeHelper.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt
=> @W-18196428: [MSDK Android] User Identity No Longer Fetched In MSDK 13.0 Due To Network On Main

libs/SalesforceSDK/build.gradle.kts, libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushMessaging.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ApiVersionStrings.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsApiClient.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/NotificationsTypesResponseBody.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/accounts/UserAccountManagerTest.java, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/PushMessagingTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/PushServiceTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceActionableNotificationContentTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/ApiVersionStringsTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/NotificationsActionsResponseBodyTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/NotificationsApiErrorResponseBodyTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/NotificationsApiExceptionTest.kt, libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/NotificationsTypesResponseBodyTest.kt
This adds the missing code coverage and unit tests from the three earlier pull requests for Actionable Notifications.  Those were merged a few weeks ago at the request of other teams whose schedule required earlier adoption.
Several small functional changes are included at the request of the adopting teams.
I drafted the changes by carefully cherry picking the relevant pull requests into a test pull request as shown below.  It's CodeCov is ~95%⭐️ mockk really was the magic that made this possible.
https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2700
While the CodeCov report looks great and the coverage itself revealed numerous bugs, there is work to be done for logical unit testing.  I added several to-do comments where we'll need additional time …
=> @W-18186860: Actionable Notifications (Android) Additional Test Automation For Code Coverage

libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/AuthenticationUtilities.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/idp/SPAuthCodeHelper.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginViewModel.kt
- User Identity no longer fetched (https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2699)
- Fix status bar icon color (https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2703)
- Make LoginActivity onAuthFlowError open (https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2707)
=> Cherry picking fixes for 13.0.1

libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LoginServerManager.java, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.kt, libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/components/PickerBottomSheet.kt
This is a set of quick bug fixes based on testing in SApp today.
=> @W-19130548: [MSDK Android] Using External Link With Login_Hint And Login_Host Duplicates Login Servers In Server Picker

libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/auth/LoginServerManagerTest.java
[I believe it was introduced here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/29eb730aa77a29a75957d0e1299c4d3541a0c5db#diff-5747e228aca68ffb0be3b2e5168483acc9508530acd1de0ec1d8b6f7cbe79cfa).
=> Fix login server manager test.
